### ISSUE TITLE
tableExists() cannot handle Database Name with dot

### ISSUE THREAD

**Issue by mbnl** [codeigniter4/CodeIgniter4#8647] opened 2024-03-21 08:29 UTC
### PHP Version

8.1

### CodeIgniter4 Version

4.4.5

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

Hello, I'm having a problem

My database name;
>com.sitedb.web

The operation I intend to perform is `tableExists('tableName')`.

When I run this code, I receive a Database Exception error. Upon detailed examination of the error, I found that CodeIgniter 4 (CI4) was sending the following MySQL command:
>SHOW TABLES FROM \`com\`.\`sitedb\`.\`web\`

### Steps to Reproduce

That should have been the right command;
>SHOW TABLES FROM \`com.sitedb.web\`

Due to the dots `.` in my database name, CI4 was treating it as \`.\`, thus causing the issue. However, since I'm using a hosting service, I cannot change the database name. Upon inspecting the source code, I found that in `system/Database/MySQLi/Connection.php`, line 391, the code was modified as follows:
>$sql = 'SHOW TABLES FROM ' . $this->escapeIdentifiers($this->database);

I identified that the problem stems from the `escapeIdentifiers` method. Instead of modifying this method, I updated the line as follows:
>"$sql = 'SHOW TABLES FROM \`' . $this->escapeLikeStringDirect($this->database).'\`';"

so that the mysql command was correctly as follows
>SHOW TABLES FROM \`com.sitedb.web\`

This solution temporarily resolved my issue. However, when I update to a new version of CI4, the old code will return, potentially causing the same error in the future. I would appreciate it if you could address this issue and provide a permanent solution.
Thank you.

### Expected Output

>SHOW TABLES FROM \`com.sitedb.web\`

**Comment by datamweb** [comment] 2024-03-21 08:39
CodeIgniter doesn’t support dots (.) in the database, table, and column names

**Comment by mbnl** [comment] 2024-03-21 08:51
> CodeIgniter doesn’t support dots (.) in the database, table, and column names

Yes, I already realized this. Since it is a hosting provider, I cannot provide a change as a database, so if a permanent solution is possible, not only me but also the errors that may occur in the future will be eliminated.

**Comment by ddevsr** [comment] 2024-03-21 09:01
@mbnl Whats a solution you have? Feel free to send PR

**Comment by kenjis** [comment] 2024-03-21 09:14
This is clearly documented.

> Note
CodeIgniter doesn’t support dots (.) in the database, table, and column names.
https://codeigniter4.github.io/CodeIgniter4/database/examples.html

Probably we cannot fix this. 
This is because it is impossible to determine whether a dot is a part of a database name or an identifier delimiter.

**Comment by kenjis** [comment] 2024-03-21 10:16
@mbnl If you have a good idea, feel free to send PRs.

**Comment by kenjis** [comment] 2024-03-21 22:37
This is not a bug, but I am reopening it for reconsideration.

**Comment by kenjis** [comment] 2024-03-21 22:44
@codeigniter4/database-team @codeigniter4/core-team 
This issue is because of `$this->escapeIdentifiers($this->database)`.
https://github.com/codeigniter4/CodeIgniter4/blob/7109931e9af0cc03edfbef47d2c39197aa213ee9/system/Database/MySQLi/Connection.php#L390-L400

Is there possibility that `$this->database` is not only a database name?
That is, may it contain a schema name?

**Comment by mbnl** [comment] 2024-03-22 05:10
> @codeigniter4/database-team @codeigniter4/core-team This issue is because of `$this->escapeIdentifiers($this->database)`.
> 
> https://github.com/codeigniter4/CodeIgniter4/blob/7109931e9af0cc03edfbef47d2c39197aa213ee9/system/Database/MySQLi/Connection.php#L390-L400
> 
> Is there possibility that `$this->database` is not only a database name? That is, may it contain a hostname or schema name?
> 
> If `$this->database` is just a database name only, we can add a new escape method for database names, and can handle a database name with dots.

Yes, only the database name. There is no prefix or hostname. It is a mysql 8.0 database created through the hosting panel.

**Comment by kenjis** [comment] 2024-03-27 02:55
The `$this->database` comes from `Config\Database`:
https://github.com/codeigniter4/CodeIgniter4/blob/d8e4de208a8714b64f61ac4187639f2c7970af07/app/Config/Database.php#L34
and it is just a database name only.
We also have `hostname` and `schema` in the config array.

So we can support database name with dots.

@mbnl I sent a PR #8664
Check it if you can.

**Comment by kenjis** [comment] 2024-03-28 02:53
Closed by #8664

**Closed by kenjis** 2024-03-28 02:53 UTC
Labels: enhancement, database
