### ISSUE TITLE
Codeigniter 4 not redirecting well. is not including the baseUrl well on redirect

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#2342] opened 2019-10-17 08:07 UTC
Hello My Pros,
How are you today please I am having issue to redirect to page.

I customise my app/Config/App.php by adding constructor to it where I auto set the base url like this
```php
public function __construct()
{
$root = (isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) && ('on' == $_SERVER['HTTPS']) ? "https://" : "http://") . $_SERVER['HTTP_HOST'];
$root .= str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']);

$this->baseURL = $root;
}
```
I want to redirect to localhost/aensd/login
Where aensd is the folder where my application is stored
And It redirect to localhost/login instead of localhost/aensd/login calling error 404

```php
if ($users->save($user))
{
// Success!

return redirect()->route('login')->with('message', lang('Auth.registerSuccess'));
}
```

I hope this is bug on the redirect path of the script. please check if there is anything you can do on this I have try to find away to solve this issue but no way then planing to code my own class which will override this.
but still need the follow come redirect so that my code will not be bulky
please help me on this

**Comment by titounnes** [comment] 2019-10-17 08:49
for discussion and question, please use https://forum.codeigniter.com

**Comment by ChibuezeAgwuDennis** [comment] 2019-10-17 09:07
> 
> 
> for discussion and question, please use https://forum.codeigniter.com

I have already report this to the forum but no respond on this

**Comment by ChibuezeAgwuDennis** [comment] 2019-10-17 09:18
I though I have solve this issue by using site_url inside the redirect method to.
that is:
```php
return redirect()->to('login')->with('message', lang('Auth.registerSuccess'));
```
Note: this does not work for:
return redirect()->route(site_url('login))->with('message', lang('Auth.registerSuccess'));
return redirect()->route(base_url('login))->with('message', lang('Auth.registerSuccess'));

this one return the initial issue
return redirect()->to(base_url('login))->with('message', lang('Auth.registerSuccess'));
return redirect()->back()->with('message', lang('Auth.registerSuccess'));

**Comment by jim-parry** [comment] 2019-10-17 09:42
Duplicate of #2119

**Closed by jim-parry** 2019-10-17 09:42 UTC

**Comment by ChibuezeAgwuDennis** [comment] 2019-10-17 10:54
hello jim parry should I replace the base_url  at requestResponse to site_url

**Comment by jim-parry** [comment] 2019-10-17 12:17
Not clear yet. We thought we had a solution, but the problem is deeper. We are working on it, snf should resolve it in the next few days.
