### ISSUE TITLE
Bug: Wrong forming sql query when using prefixes (protectIdentifiers)

### ISSUE THREAD

**Issue by GregorKocar** [codeigniter4/CodeIgniter4#6171] opened 2022-06-22 01:32 UTC
### PHP Version

7.3

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

When using prefixes in database, and you make query (through builder and calling countAllResults) using "where" clause and you already include table with prefix you get this error:
"Unknown column 'tr_`tr_clients.client_Name' in where clause" 
So prefix tr_ is added twice. (bug in BaseConnection.php)

### Steps to Reproduce

- Use database with prefixes and set prefix in env file
- Execute select query with "where/like" clause (via countAllResults)

### Expected Output

It shouldn't happen that prefix would be appended twice. So proper formation of SQL in my case should be WHERE `tr_clients`.`client_Name` LIKE

### Anything else?

I found a solution to fix this bug. Under function protectIdentifiers (BaseConnection) you have to add following code:
```
            $hasescapechar=$firstSegment!=$parts[0]; //ADDED
            // Is there a table prefix defined in the config file? If not, no need to do anything
            if ($this->DBPrefix !== '') {
```
...
```
                // We only add the table prefix if it does not already exist
                elseif (strpos(trim($parts[$i], $this->escapeChar), $this->DBPrefix) !== 0) { //TRIM and COMPARE
                    $parts[$i] = ($hasescapechar?$this->escapeChar:'').$this->DBPrefix . $parts[$i].($hasescapechar?$this->escapeChar:''); //ADD escape char if it was there before
                    
```
                }

**Comment by kenjis** [comment] 2022-06-22 01:45
> Execute select query with "where/like" clause (via countAllResults)

Can you show the example code?

**Comment by kenjis** [comment] 2022-06-22 02:08
duplicate of #5917 ?

**Comment by kenjis** [comment] 2022-06-22 02:11
@GregorKocar Please update to 4.2.2 and check this issue.
If you have still the issue, feel free to reopen.

**Closed by kenjis** 2022-06-22 02:11 UTC
Labels: bug, database
