### ISSUE TITLE
Spark no longer trigger pre_system and post_system events

### ISSUE THREAD

**Issue by Martin-4Spaces** [codeigniter4/CodeIgniter4#8442] opened 2024-01-21 12:46 UTC
### PHP Version

8.3

### CodeIgniter4 Version

4.4.4

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

apache

### What happened?

After updating CodeIgniter, some commands broke.
The problems are caused by some code not being executed. Code that fired when events such as pre_system and post_system are triggered.

### Steps to Reproduce

1. Subscribe to "pre_system" event and print some debug data
2. Run a command with spark
3. See that the debugging data is not printed

### Expected Output

I expect spark to fire pre_system and post_system events.
After some research I found this commit, https://github.com/codeigniter4/CodeIgniter4/commit/775fa7d4e329209042269ae8c1bebb543c9d1c42, which moved spark commands outside the CodeIgniter::run method. 

### Anything else?

I've searched the documentation and changelogs for info about this change. But wittout luck.
Will look for a workaround for now.

**Comment by kenjis** [comment] 2024-01-21 21:29
Sorry, but this is not a bug.
Because these event points are for controllers, not for spark commands.
It was a bug that Spark triggered `pre_system` and `post_system` events.

https://codeigniter4.github.io/CodeIgniter4/extending/events.html#event-points
- `pre_system` Called early during system execution. The URI, Request, and Response have been instantiated, but page cache checking, routing, and execution of “before” controller filters have not yet occurred.
- `post_system` Called right before the final rendered page is sent to the browser, at the end of system execution, after the execution of “after” controller filters.

**Comment by kenjis** [comment] 2024-01-21 21:35
By the way, what do you want to do with these events when you run spark commands?

Probably you can fire these events if you extends `CodeIgniter\CLI\Console::run()`.

**Comment by Martin-4Spaces** [comment] 2024-01-22 09:38
Use cases: External libraries that extend code igniter use `pre_system` to setup. 
E.g
- Extending routing to add API management capabilities. I use commands to interact with this extension. 
- Extending exception handler 

`pre_system` and `post_system` have been a reliable way for extensions to initialize and exit. 

Since commands have access to the CodeIgniter system, such as cache, config, cookies, email, files, etc. I would argue these events should be fired when commands are running.

**Comment by kenjis** [comment] 2024-01-22 09:51
I don't understand why a CLI command has something to do with routing.
Can I have a look at such a external library?

Spark is not for web applications, but for console applications.
And we separated them completely in v4.3.0. See #6110

**Comment by Martin-4Spaces** [comment] 2024-01-22 10:16
Routes can be stored in a database for API management purposes. Migrations/Seeds is used to save new routes. Spark is used to run migrations/seeds.
Here is an example of such a library https://github.com/4spacesdk/CI4RESTExtension/blob/master/Hooks.php 
This is of cause just one example. Other libraries could benefit from these events. It is however always possible to find other solutions.

I have implemented a workaround that suites my CI4.4 project. And I will have to look for a replacement for `pre_system` and `post_system` in my libraries. Since I can't seem to convince you of the value of events like these. :)

**Comment by kenjis** [comment] 2024-01-22 10:54
Perhaps it is possible to add event points for Spark commands.

Let's wait and see what others have to say.

**Comment by kenjis** [comment] 2024-01-23 03:40
How about adding `pre_command` and `post_command`?

and If anyone is going to implement this, please send a PR to branch `4.5`.
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

**Comment by kenjis** [comment] 2024-02-01 06:20
@Martin-4Spaces Check #8496

**Comment by Martin-4Spaces** [comment] 2024-02-01 08:00
Awesome @kenjis ! Thank you.

**Comment by kenjis** [comment] 2024-02-04 23:54
Closed by #8496

**Closed by kenjis** 2024-02-04 23:54 UTC
Labels: enhancement, 4.5
