### ISSUE TITLE
Bug: Environment development

### ISSUE THREAD

**Issue by esjdev** [codeigniter4/CodeIgniter4#5017] opened 2021-08-22 15:52 UTC
**Describe the bug**
The development environment has an error configuring it in .env as shown in the image below:

![Alternate image text](https://i.imgur.com/oVOcYrC.png)

**CodeIgniter 4 version**
CI 4.1.3

**Expected behavior, and steps to reproduce if appropriate**
Download the project manually or via composer, then configure the .env

**Context**
 - PHP version 7.4

**Comment by esjdev** [comment] 2021-08-22 16:31
I was giving somes F5 and the error disappeared, why he is showing the error I don't know, maybe some ngix cache.

**Comment by esjdev** [comment] 2021-08-22 16:37
Error reappeared, could be something with ngix.

However I use the Docker, only with the codeigniter this is giving a problem :(

**Comment by paulbalandan** [comment] 2021-08-24 13:35
This would be hard to tell if a bug with CodeIgniter considering that the shutdown handler catches the fatal error.

However, I am led to believe this is not a bug with the framework since the fatal error tells us an empty filename in Unknown. For one, I can see that error message if there is a misconfiguration in the php itself, perhaps wrong ini settings or misconfigured extensions. If you can check this against non-Docker environments and/or different servers aside from nginx, then we'll see if the problem still persists.

For now I'll be closing this but feel free to continue the conversation if you found anything.

**Closed by paulbalandan** 2021-08-24 13:35 UTC
Labels: bug
