### ISSUE TITLE
Bug: CURLrequest deadlock on cookie

### ISSUE THREAD

**Issue by xbotkaj** [codeigniter4/CodeIgniter4#4035] opened 2020-12-28 07:52 UTC
**Describe the bug**
Using cookies and making CURL request to the same machine makes deadlock. CURL request should not populate Cookie to header (for local development) because it will wait until the first request will finish to unlock cookie and then it will have access to cookie resource. 

Example:
`$client = Services::curlrequest();
$response = $client->request('GET', 'http://localhost');`

This will result in deadlock and waiting for the response. (Sometimes it will make run once and makes deadlock on the second run)

**CodeIgniter 4 version**
4.0.4 develop - latest

**Affected module(s)**
CURLrequest

**Expected behavior, and steps to reproduce if appropriate**
Processing CURLrequest without deadlock.

**Context**
 - OS: Windows 8.1
 - Apache 2.4
 - PHP version 7.4

P.S. i also tried 'cookie' option like this and with static name of file:
`$tempCode = substr(bin2hex(random_bytes(10)),0,10);
		$curlresponse = $client->request('GET', 'http://localhost/',['cookie' => WRITEPATH . $tempCode . '_CookieSaver.txt']);`

**Comment by xbotkaj** [comment] 2020-12-28 13:58
In the end it was seassion lock. We can avoid it with this:

> 		// Stop session to avoid deadlock

		if($this->config['session'])
		{
			session_write_close();
		}

		// Send the request and wait for a response.
		$output = curl_exec($ch);

		// Resume session
		if($this->config['session'])
		{
			session_start();
		}

**Comment by paulbalandan** [comment] 2021-01-27 02:01
Can you send in a PR?

**Comment by michalsn** [comment] 2021-02-05 06:30
By default, the `CURLRequest` class copies all global headers if no custom headers are given. Have you tried adding custom headers?

```php
$client = Services::curlrequest(); 
$response = $client->request('GET', 'http://localhost', [
	'headers' => [
		'User-Agent' => 'hello/1.0'
	]
]);
```

**Comment by xbotkaj** [comment] 2021-02-07 17:30
> By default, the `CURLRequest` class copies all global headers if no custom headers are given. Have you tried adding custom headers?
> 
> ```
> $client = Services::curlrequest(); 
> $response = $client->request('GET', 'http://localhost', [
> 	'headers' => [
> 		'User-Agent' => 'hello/1.0'
> 	]
> ]);
> ```

Yes of course, but I want to use my session ID to be passed and used, the same as I would make call to the server.

**Comment by michalsn** [comment] 2021-02-07 21:04
In that case, it's not a bug. You should create a new session and not try to use the current one with the CURL call.

In general, I find strange what you're trying to do here, but I guess you have a valid use case for this. Personally, I don't think we should promote this type of functionality inside the framework (my first impression is bad design). If you really need this type of functionality I would suggest overriding this service with your own version - it's very easy.

**Comment by paulbalandan** [comment] 2021-09-09 04:15
Closing based on https://github.com/codeigniter4/CodeIgniter4/issues/4035#issuecomment-774762469

**Closed by paulbalandan** 2021-09-09 04:15 UTC
Labels: bug
