### ISSUE TITLE
Bug: The model fails to save entities when they have internal entities.

### ISSUE THREAD

**Issue by Patricio-Byte-Solution** [codeigniter4/CodeIgniter4#6336] opened 2022-08-03 06:45 UTC
### PHP Version

8.0

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

The model fails to save entities when they have internal entities. This occurs because of an error in the code in `system\Model.php`. Specifically in the function `objectToRawArray()`.
When "`parent::objectToRawArray($data, $onlyChanged);` " is called in that function, the parameter "`$recursive`" is missing.

```php
    /**
     * Takes a class an returns an array of it's public and protected
     * properties as an array with raw values.
     *
     * @param object|string $data
     * @param bool          $recursive If true, inner entities will be casted as array as well
     *
     * @throws ReflectionException
     *
     * @return array|null Array
     */
    protected function objectToRawArray($data, bool $onlyChanged = true, bool $recursive = false): ?array
    {
        $properties = parent::objectToRawArray($data, $onlyChanged);

        // Always grab the primary key otherwise updates will fail.
        if (
            method_exists($data, 'toRawArray') && (! empty($properties) && ! empty($this->primaryKey) && ! in_array($this->primaryKey, $properties, true)
            && ! empty($data->{$this->primaryKey}))
        ) {
            $properties[$this->primaryKey] = $data->{$this->primaryKey};
        }

        return $properties;
    }
```

### Steps to Reproduce

```php
$entityFather = new FatherEntity();

$entityFather->name      = 'Patricio';
$entityFather->sonEntity = new SonEntity([ 'name' => 'Maximo', 'age' => 18 ]);

// Get the raw array with $onlyChanged = false and $recursive = true
$rawArray = $entityFather->toRawArray(false,true);

// $rawArray is now:
Array(
     'name'      => 'Patricio',
     'sonEntity' => SonEntity Object (
        ....
        ...
    )
)
```

### Expected Output

```
// $rawArray should be

Array(
    'name'      => 'Patricio',
    'sonEntity' => Array(
        'name'    => 'Maximo',
        'age'     => '18',
    )
)
```

### Anything else?

Thank you very much for your work.

**Comment by kenjis** [comment] 2022-08-03 07:11
Duplicate of #4360 ?

**Comment by MGatner** [comment] 2022-08-19 10:38
Maybe need to revive #4368? @najdanovicivan are you available/interested to complete that?

**Comment by najdanovicivan** [comment] 2022-08-19 21:08
@MGatner I’m willing to work on this one but I’m currently on vacation. I wont be able to start working on this one before the September 5th

**Comment by MGatner** [comment] 2022-08-20 10:52
Not a problem! We're all volunteers doing what we can when we can 🤗 If this isn't feasible for you then please speak up so others will take it on - no judgement whatsoever (I haven't written code for CI4 in months).

**Comment by ping-yee** [comment] 2022-08-26 16:51
Does this issue has been solved at current develop branch?
Because I can't reproduce the output by using the same `Steps to Reproduce` code.

![image](https://user-images.githubusercontent.com/65348108/186953297-cb41437e-e0e4-4663-b953-9adb20fa69ca.png)

This is the output what I get, as this image shows that the type of sonEntity is `array` without `SonEntity Object`.

**Comment by kenjis** [comment] 2022-08-27 01:14
> Does this issue has been solved at current develop branch?

Yes, I cannot reproduce the issue.

On `develop` branch.

```php
<?php

namespace App\Controllers;

use CodeIgniter\Entity\Entity;

class Home extends BaseController
{
    public function index()
    {
        $entityFather = new Entity();

        $entityFather->name      = 'Patricio';
        $entityFather->sonEntity = new Entity(['name' => 'Maximo', 'age' => 18]);

        $rawArray = $entityFather->toRawArray(false, true);

        dd($rawArray);
    }
}
```
```console
$ php public/index.php 

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ $rawArray                                                                                                                          │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
array (2) [
    'name' => string (8) "Patricio"
    'sonEntity' => array (2) [
        'name' => string (6) "Maximo"
        'age' => integer 18
    ]
]
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Called from .../app/Controllers/Home.php:18 [dd()]
```

**Comment by kenjis** [comment] 2022-08-27 02:02
> The model fails to save entities when they have internal entities. This occurs because of an error in the code in `system\Model.php`. Specifically in the function `objectToRawArray()`.
When "`parent::objectToRawArray($data, $onlyChanged);` " is called in that function, the parameter "`$recursive`" is missing.

https://github.com/codeigniter4/CodeIgniter4/blob/6234f0ed45c66da356f88255e831336978b3127d/system/Model.php#L706-L708

I don't know this is a bug or not.

**Closed** 2022-08-27 02:03 UTC

**Comment by MGatner** [comment] 2022-08-27 09:46
> I don't know this is a bug or not.

Looks like it to me!
