### ISSUE TITLE
Bug: Models, useSoftDeletes not found in findAll

### ISSUE THREAD

**Issue by danielMonroy96** [codeigniter4/CodeIgniter4#2658] opened 2020-03-02 20:19 UTC
**Bug**
When obtaining records using findAll () and using useSoftDeletes in true, the method returns all records when it can return while $ this-> deletedField is null

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
Codeigniter\Model

**Comment by musmanikram** [comment] 2020-03-03 20:51
@danielMonroy96 Can you post some code. Because i checked tests and they worked as expected.
If you can post some code, will help to fix this

**Comment by danielMonroy96** [comment] 2020-03-03 22:00
![Captura de pantalla de 2020-03-03 15-54-35](https://user-images.githubusercontent.com/45611570/75823389-4e9abd80-5d67-11ea-9f07-b871273c5c1f.png)
![Captura de pantalla de 2020-03-03 15-55-43](https://user-images.githubusercontent.com/45611570/75823577-9cafc100-5d67-11ea-9695-585a1e13571e.png)

![Captura de pantalla de 2020-03-03 15-57-54](https://user-images.githubusercontent.com/45611570/75823805-029c4880-5d68-11ea-8cd7-ffe8a012e9a3.png)


This is my code.

**Comment by danielMonroy96** [comment] 2020-03-03 22:01
Thanks for your help, in the first consultation it does not give me the expected results

**Comment by Instrye** [comment] 2020-03-04 00:50
`deleted_at` default value?

**Comment by danielMonroy96** [comment] 2020-03-04 00:53
![Captura de pantalla de 2020-03-03 18-52-11](https://user-images.githubusercontent.com/45611570/75833930-28cde280-5d80-11ea-92d3-a66a76afa434.png)

My model!

**Comment by Instrye** [comment] 2020-03-04 01:00
i want see you table structure. and row line.
ex: 
![image](https://user-images.githubusercontent.com/9927289/75834304-93216a00-5df6-11ea-9ef9-c20f71027417.png)

![image](https://user-images.githubusercontent.com/9927289/75834273-800e9a00-5df6-11ea-958d-26a0291bd79a.png)

**Comment by danielMonroy96** [comment] 2020-03-04 01:04
![Captura de pantalla de 2020-03-03 19-02-31](https://user-images.githubusercontent.com/45611570/75834439-94647f80-5d81-11ea-81e8-157f2e309de1.png)
![Captura de pantalla de 2020-03-03 19-03-51](https://user-images.githubusercontent.com/45611570/75834491-bfe76a00-5d81-11ea-9857-72ba2aad836a.png)

thanks

**Comment by Instrye** [comment] 2020-03-04 02:09
everything is normal.
![image](https://user-images.githubusercontent.com/9927289/75837548-21e6b480-5e00-11ea-9687-dd4634ff7cac.png)

![image](https://user-images.githubusercontent.com/9927289/75837528-11ced500-5e00-11ea-9331-b83598aa8e45.png)

**Comment by danielMonroy96** [comment] 2020-03-04 14:01
I'll try updating CI, because the problem persists

**Comment by arif-rh** [comment] 2020-03-06 23:47
@danielMonroy96  If I see your code, It seems the issue is not from the Model but in your logic code

![logic flow](https://user-images.githubusercontent.com/2386359/76130981-42e91880-603f-11ea-9b79-6a8faeee0a8b.png)

I have tried to reproduce the issue but everything seem right. So can you confirm again, is your logic code is right?

**Comment by danielMonroy96** [comment] 2020-03-09 15:30
Apparently yes, I have already compared my code with colleagues and it
works fine! Maybe it's my environment, thanks for your help and response

Good day!!

**Comment by MGatner** [comment] 2020-03-09 19:13
@danielMonroy96 is this issue resolved? If so feel free to close it.

**Comment by leutamo** [comment] 2020-05-31 19:15
Hi everyone, i have same problem. i read the answer from Instrye, and all works fine.
the problem its in the Database fields, this suppose that not work's with int values(deleted_at)?.
well, with datetime in database works pretty :)
Thanks all!! only here found the answer thanks Instrye!!! you rock'ss!!
best regards!

**Comment by michalsn** [comment] 2020-06-22 16:26
This seems like resolved.

**Closed by michalsn** 2020-06-22 16:26 UTC
Labels: bug

**Comment by JJohanGH** [comment] 2020-10-28 21:55
Para resolver este problema, yo lo hice ded esta manera:
entre a vendor\codeigniter4\framework\system\Model.php o sea el modelo que estas extendiendo
corregí la function findAll:

`
public function findAll(int $limit = 0, int $offset = 0)
	{
		$builder = $this->builder();

		if ($this->tempUseSoftDeletes === true)
		{
			#$builder->where($this->table . '.' . $this->deletedField, null); -- JJohan 20201028 
			$builder->where($this->table . '.' . $this->deletedField, null);
		}

		$row = $builder->limit($limit, $offset)
				->get();

		$row = $row->getResult($this->tempReturnType);

		$eventData = $this->trigger('afterFind', ['data' => $row, 'limit' => $limit, 'offset' => $offset]);

		$this->tempReturnType     = $this->returnType;
		$this->tempUseSoftDeletes = $this->useSoftDeletes;

		return $eventData['data'];
	}
`

**Comment by tanviet12** [comment] 2021-11-21 06:40
This bug occurs when:

- `$useSoftDeletes = true`

- `deleted_at` column with data type is timestamp.

Run this query to change  `deleted_at` from  timestamp to datetime:

```
alter table `your_table` modify column `deleted_at` datetime DEFAULT NULL;
```
