### ISSUE TITLE
Bug: Am getting an error when installing composer dependencies

### ISSUE THREAD

**Issue by Elvis254** [codeigniter4/CodeIgniter4#9149] opened 2024-08-25 19:59 UTC
### PHP Version

8.2

### CodeIgniter4 Version

4.5.4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.2

### What happened?

I got the error below when I executed `composer install` on the command line.

```
Class Laminas\Escaper\Escaper located in ./system/ThirdParty/Escaper/Escaper.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Laminas\Escaper\Exception\ExceptionInterface located in ./system/ThirdParty/Escaper/Exception/ExceptionInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Laminas\Escaper\Exception\InvalidArgumentException located in ./system/ThirdParty/Escaper/Exception/InvalidArgumentException.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Laminas\Escaper\Exception\RuntimeException located in ./system/ThirdParty/Escaper/Exception/RuntimeException.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\CallFinder located in ./system/ThirdParty/Kint/CallFinder.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\FacadeInterface located in ./system/ThirdParty/Kint/FacadeInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Kint located in ./system/ThirdParty/Kint/Kint.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\AbstractPlugin located in ./system/ThirdParty/Kint/Parser/AbstractPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ArrayLimitPlugin located in ./system/ThirdParty/Kint/Parser/ArrayLimitPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ArrayObjectPlugin located in ./system/ThirdParty/Kint/Parser/ArrayObjectPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\Base64Plugin located in ./system/ThirdParty/Kint/Parser/Base64Plugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\BinaryPlugin located in ./system/ThirdParty/Kint/Parser/BinaryPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\BlacklistPlugin located in ./system/ThirdParty/Kint/Parser/BlacklistPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ClassMethodsPlugin located in ./system/ThirdParty/Kint/Parser/ClassMethodsPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ClassStaticsPlugin located in ./system/ThirdParty/Kint/Parser/ClassStaticsPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ClosurePlugin located in ./system/ThirdParty/Kint/Parser/ClosurePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ColorPlugin located in ./system/ThirdParty/Kint/Parser/ColorPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ConstructablePluginInterface located in ./system/ThirdParty/Kint/Parser/ConstructablePluginInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\DateTimePlugin located in ./system/ThirdParty/Kint/Parser/DateTimePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\DOMDocumentPlugin located in ./system/ThirdParty/Kint/Parser/DOMDocumentPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\EnumPlugin located in ./system/ThirdParty/Kint/Parser/EnumPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\FsPathPlugin located in ./system/ThirdParty/Kint/Parser/FsPathPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\IteratorPlugin located in ./system/ThirdParty/Kint/Parser/IteratorPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\JsonPlugin located in ./system/ThirdParty/Kint/Parser/JsonPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\MicrotimePlugin located in ./system/ThirdParty/Kint/Parser/MicrotimePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\MysqliPlugin located in ./system/ThirdParty/Kint/Parser/MysqliPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\Parser located in ./system/ThirdParty/Kint/Parser/Parser.php does not comply with psr-4 autoloading standard 
(rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\PluginInterface located in ./system/ThirdParty/Kint/Parser/PluginInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ProxyPlugin located in ./system/ThirdParty/Kint/Parser/ProxyPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\SerializePlugin located in ./system/ThirdParty/Kint/Parser/SerializePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\SimpleXMLElementPlugin located in ./system/ThirdParty/Kint/Parser/SimpleXMLElementPlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\SplFileInfoPlugin located in ./system/ThirdParty/Kint/Parser/SplFileInfoPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\SplObjectStoragePlugin located in ./system/ThirdParty/Kint/Parser/SplObjectStoragePlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\StreamPlugin located in ./system/ThirdParty/Kint/Parser/StreamPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\TablePlugin located in ./system/ThirdParty/Kint/Parser/TablePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ThrowablePlugin located in ./system/ThirdParty/Kint/Parser/ThrowablePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\TimestampPlugin located in ./system/ThirdParty/Kint/Parser/TimestampPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\ToStringPlugin located in ./system/ThirdParty/Kint/Parser/ToStringPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\TracePlugin located in ./system/ThirdParty/Kint/Parser/TracePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Parser\XmlPlugin located in ./system/ThirdParty/Kint/Parser/XmlPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\AbstractRenderer located in ./system/ThirdParty/Kint/Renderer/AbstractRenderer.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\CliRenderer located in ./system/ThirdParty/Kint/Renderer/CliRenderer.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\PlainRenderer located in ./system/ThirdParty/Kint/Renderer/PlainRenderer.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\RendererInterface located in ./system/ThirdParty/Kint/Renderer/RendererInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\AbstractPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/AbstractPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\ArrayLimitPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/ArrayLimitPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\BinaryPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/BinaryPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\BlacklistPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/BlacklistPlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\CallablePlugin located in ./system/ThirdParty/Kint/Renderer/Rich/CallablePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\ClosurePlugin located in ./system/ThirdParty/Kint/Renderer/Rich/ClosurePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\ColorPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/ColorPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\DepthLimitPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/DepthLimitPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\MethodDefinitionPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/MethodDefinitionPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\MicrotimePlugin located in ./system/ThirdParty/Kint/Renderer/Rich/MicrotimePlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\PluginInterface located in ./system/ThirdParty/Kint/Renderer/Rich/PluginInterface.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\RecursionPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/RecursionPlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\SimpleXMLElementPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/SimpleXMLElementPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\SourcePlugin located in ./system/ThirdParty/Kint/Renderer/Rich/SourcePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\TablePlugin located in ./system/ThirdParty/Kint/Renderer/Rich/TablePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\TabPluginInterface located in ./system/ThirdParty/Kint/Renderer/Rich/TabPluginInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\TimestampPlugin located in ./system/ThirdParty/Kint/Renderer/Rich/TimestampPlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\TraceFramePlugin located in ./system/ThirdParty/Kint/Renderer/Rich/TraceFramePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Rich\ValuePluginInterface located in ./system/ThirdParty/Kint/Renderer/Rich/ValuePluginInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\RichRenderer located in ./system/ThirdParty/Kint/Renderer/RichRenderer.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\AbstractPlugin located in ./system/ThirdParty/Kint/Renderer/Text/AbstractPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\ArrayLimitPlugin located in ./system/ThirdParty/Kint/Renderer/Text/ArrayLimitPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\BlacklistPlugin located in ./system/ThirdParty/Kint/Renderer/Text/BlacklistPlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\DepthLimitPlugin located in ./system/ThirdParty/Kint/Renderer/Text/DepthLimitPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\EnumPlugin located in ./system/ThirdParty/Kint/Renderer/Text/EnumPlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\MicrotimePlugin located in ./system/ThirdParty/Kint/Renderer/Text/MicrotimePlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\PluginInterface located in ./system/ThirdParty/Kint/Renderer/Text/PluginInterface.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\RecursionPlugin located in ./system/ThirdParty/Kint/Renderer/Text/RecursionPlugin.php does not comply 
with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\Text\TracePlugin located in ./system/ThirdParty/Kint/Renderer/Text/TracePlugin.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Renderer\TextRenderer located in ./system/ThirdParty/Kint/Renderer/TextRenderer.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Utils located in ./system/ThirdParty/Kint/Utils.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\BlobValue located in ./system/ThirdParty/Kint/Zval/BlobValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\ClosureValue located in ./system/ThirdParty/Kint/Zval/ClosureValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\DateTimeValue located in ./system/ThirdParty/Kint/Zval/DateTimeValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\EnumValue located in ./system/ThirdParty/Kint/Zval/EnumValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\InstanceValue located in ./system/ThirdParty/Kint/Zval/InstanceValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\MethodValue located in ./system/ThirdParty/Kint/Zval/MethodValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\ParameterHoldingTrait located in ./system/ThirdParty/Kint/Zval/ParameterHoldingTrait.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\ParameterValue located in ./system/ThirdParty/Kint/Zval/ParameterValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\Representation\ColorRepresentation located in ./system/ThirdParty/Kint/Zval/Representation/ColorRepresentation.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\Representation\MethodDefinitionRepresentation located in ./system/ThirdParty/Kint/Zval/Representation/MethodDefinitionRepresentation.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\Representation\MicrotimeRepresentation located in ./system/ThirdParty/Kint/Zval/Representation/MicrotimeRepresentation.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\Representation\Representation located in ./system/ThirdParty/Kint/Zval/Representation/Representation.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\Representation\SourceRepresentation located in ./system/ThirdParty/Kint/Zval/Representation/SourceRepresentation.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\Representation\SplFileInfoRepresentation located in ./system/ThirdParty/Kint/Zval/Representation/SplFileInfoRepresentation.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\ResourceValue located in ./system/ThirdParty/Kint/Zval/ResourceValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\SimpleXMLElementValue located in ./system/ThirdParty/Kint/Zval/SimpleXMLElementValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\StreamValue located in ./system/ThirdParty/Kint/Zval/StreamValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\ThrowableValue located in ./system/ThirdParty/Kint/Zval/ThrowableValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\TraceFrameValue located in ./system/ThirdParty/Kint/Zval/TraceFrameValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\TraceValue located in ./system/ThirdParty/Kint/Zval/TraceValue.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Kint\Zval\Value located in ./system/ThirdParty/Kint/Zval/Value.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Psr\Log\AbstractLogger located in ./system/ThirdParty/PSR/Log/AbstractLogger.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Psr\Log\InvalidArgumentException located in ./system/ThirdParty/PSR/Log/InvalidArgumentException.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Psr\Log\LoggerAwareInterface located in ./system/ThirdParty/PSR/Log/LoggerAwareInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Psr\Log\LoggerAwareTrait located in ./system/ThirdParty/PSR/Log/LoggerAwareTrait.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Psr\Log\LoggerInterface located in ./system/ThirdParty/PSR/Log/LoggerInterface.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Psr\Log\LoggerTrait located in ./system/ThirdParty/PSR/Log/LoggerTrait.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Psr\Log\LogLevel located in ./system/ThirdParty/PSR/Log/LogLevel.php does not comply with psr-4 autoloading standard (rule: CodeIgniter\ => ./system). Skipping.
Class Psr\Log\NullLogger located in ./system/ThirdParty/PSR/Log/NullLogger.php does not comply with psr-4 autoloading standard 
(rule: CodeIgniter\ => ./system). Skipping.
```

### Steps to Reproduce

Make the classes indicated in the error comply with psr-4 autoloading standard. Abide by the set rule include `CodeIgniter\` prefix when writing the namespace statement in a class within the system folder.

### Expected Output

No error should be produced when `composer install` is executed on the command line.

**Comment by kenjis** [comment] 2024-08-26 02:51
Duplicate of #8951

**Closed by kenjis** 2024-08-26 02:51 UTC
Labels: bug, duplicate
