### ISSUE TITLE
Bug: Data is stored, but does not encrypt the password

### ISSUE THREAD

**Issue by memiljamel** [codeigniter4/CodeIgniter4#5504] opened 2021-12-25 14:47 UTC
### PHP Version

7.3

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL

### What happened?

Why is this not working?

1. Data is stored, but does not encrypt the password.
// File: MyEntities()
```
public function setPassword(string $password)
{
         $this->attributes['password'] = password_hash($password, PASSWORD_DEFAULT);

          return $this;
}
```

// File: MyController.php
```
$model = new MyModel();
$entities = new MyEntities();
$entities->fill($this->request->getPost());
$model->insert($entities)
```

2. There are no error messages and the data is not stored in the database.

// File: MyController.php
```
$model = new MyModel();
$model->insert([
          'field1' => $this->request->getPost('field1'),
          'field2' => $this->request->getPost('field2'),
          'field3' => $this->request->getPost('field3'),
]);
```

I'm stuck and can't find a solution to this problem? And if I look at the documentation what I do is as the documentation describes.

### Steps to Reproduce

-

### Expected Output

Results not as expected.

**Comment by kenjis** [comment] 2021-12-25 20:57
Can't reproduce.

```php
<?php

namespace App\Entities;

use CodeIgniter\Entity\Entity;

class MyEntities extends Entity
{
    protected $dates   = ['created_at', 'updated_at'];

    public function setPassword(string $password)
    {
        $this->attributes['password'] = password_hash($password, PASSWORD_DEFAULT);

        return $this;
    }
}
```

```php
<?php

namespace App\Models;

use CodeIgniter\Model;

class MyModel extends Model
{
    protected $table            = 'my_model';
    protected $allowedFields    = ['username', 'password'];
}
```

```php
<?php

namespace App\Controllers;

use App\Entities\MyEntities;
use App\Models\MyModel;

class MyController extends BaseController
{
    public function index()
    {
        helper('form');

        echo form_open('mycontroller/post');
        echo form_input('username');
        echo form_input('password');
        echo form_submit('submit', 'Submit');
    }

    public function post()
    {
        $model = new MyModel();
        $entities = new MyEntities();
        $entities->fill($this->request->getPost());
        $model->insert($entities);
    }
}
```

```
> SELECT id, username, password FROM my_model;
+--+--------+------------------------------------------------------------+
|id|username|password                                                    |
+--+--------+------------------------------------------------------------+
|1 |username|$2y$10$y9Bsg.4Zun0dkQVV8HQBV.DLuKs/cmqopCqC9VNDM1uKFKdSWXqLS|
+--+--------+------------------------------------------------------------+
```

**Comment by memiljamel** [comment] 2021-12-26 05:42
Looks like your code snippet is working fine, because the field name for the password uses "password". In my case the field name I use is "kata_sandi" either in the database field or the name in the input type. Here the password is not encrypted.

**Comment by lonnieezell** [comment] 2021-12-26 05:54
The field name must match the name of the `setX` method (minus `set`) in order for it to find the method. Since the HTML input name isn't `password`, the Entity class has no way to know it's supposed to run the `setPassword` method. 

I don't remember how it handles underscores during the conversion, but if the input name in the HTML is `kata_sandi`, then the method name must be `setKataSandi`, or maybe `setKata_Sandi`. 

This does not appear to be a bug in the framework. I'm closing for now but feel free to discuss more. We can always reopen if we need to.

**Closed by lonnieezell** 2021-12-26 05:54 UTC

**Comment by memiljamel** [comment] 2021-12-26 06:32
Yes, you are right. I'm not very thorough in reading the documentation. Now the password can be encrypted, but if I dd($entities) the password field no longer lists the datetime as in the confirm password field. And if I $model->insert($entities) the data is not saved into the database. [https://i.postimg.cc/Pr7vWgsV/Capture.png](url)

**Comment by kenjis** [comment] 2021-12-26 07:26
You must set all the column names in `$allowedFields` to save.
Did you?
