### ISSUE TITLE
Call to a member function setContentType() on null - Responsetrait

### ISSUE THREAD

**Issue by davodm** [codeigniter4/CodeIgniter4#4524] opened 2021-04-06 15:55 UTC
Hi, I had a similar problem as described in the forum, but I didn't see any fix yet, so I decided to post the bug here for fixing in the future.
https://forum.codeigniter.com/thread-77516.html

The bug occurred on response API with this error:
Call to a member function setContentType() on null - on line 114 Responsetrait.php

Its also fixed as it described in the topic:
`
public function respond($data = null, int $status = null, string $message = '')
{
$this->response=service('response'); 
`

 - Web server Apache 2.4.46
 - PHP version 7.4

**Comment by paulbalandan** [comment] 2021-04-06 16:30
How are you using the ResponseTrait in your code? Can you a sample?

**Comment by paulbalandan** [comment] 2021-04-06 16:32
A class using a trait should be responsible for ensuring that the properties used by the trait is available when the trait will be using it. It is not the responsibility of trait to reinitialize a property that is of the class. Pending sample code, I see this as an implementation mistake on user's code.

**Comment by iRedds** [comment] 2021-04-06 16:41
Upgrade the framework to version 4.0.5 if you are using php 7.2, or to version 4.1.1 if you are using php >= 7.3 

The response property of the controller is defined in the initialization method.
If it is null, then you have changed the initialization method.

**Comment by davodm** [comment] 2021-04-06 18:39
I'm currently using CI 4.1.1 & PHP 7.4 as I mentioned before.
Here is my usage:
```
public function error($status,$msg,$data){
   return $this->setResponseFormat('json')->respond([
      'status'=>$status,
      'msg'=>$msg,
      'data'=>$data
   ]);
}
```
And it's the error:
```
CRITICAL - 2021-04-06 18:33:24 --> Call to a member function setContentType() on null
#0 F:\xampp\htdocs\recovermsg\vendor\codeigniter4\framework\system\API\ResponseTrait.php(114): App\Libraries\Api->format(Array)
#1 F:\xampp\htdocs\recovermsg\app\Libraries\Api.php(28): App\Libraries\Api->respond(Array)
#2 F:\xampp\htdocs\recovermsg\app\Controllers\ApiV1\Log.php(29): App\Libraries\Api->success('Activity succes...')
#3 F:\xampp\htdocs\recovermsg\vendor\codeigniter4\framework\system\CodeIgniter.php(936): App\Controllers\ApiV1\Log->index()
#4 F:\xampp\htdocs\recovermsg\vendor\codeigniter4\framework\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ApiV1\Log))
#5 F:\xampp\htdocs\recovermsg\vendor\codeigniter4\framework\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 F:\xampp\htdocs\recovermsg\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
```
Unfortunately, I don't get the initialization method solution. I'm just using "use ResponseTrait;" like the [document](https://codeigniter4.github.io/userguide/outgoing/api_responses.html).

**Comment by iRedds** [comment] 2021-04-06 21:58
ResponseTrait is used in controllers.
If you use it elsewhere, you must initialize the required components yourself.

**Comment by davodm** [comment] 2021-04-07 06:36
Aha, got it, May I ask you to tell me how to initialize the required components in a Library?

**Comment by paulbalandan** [comment] 2021-04-07 07:13
If you are using the trait in the context of a library, you should be initializing the response in the constructor.

```php
use Config\Services;
use CodeIgniter\API\ResponseTrait;

class MyLibrary
{
    use ResponseTrait;

    protected $response;

    public function __construct()
    {
        $this->response = Services::response();
    }

    // other code
}
```

**Comment by paulbalandan** [comment] 2021-04-07 07:13
Closing as not a bug.

**Closed by paulbalandan** 2021-04-07 07:13 UTC
Labels: waiting for info

**Comment by suwidadi** [comment] 2022-08-11 03:51
Sorry to jump in the old thread. I believe this correlates with the error I experienced when I put ResponseTrait on a constructor. is it "illegal" if I put in a constructor?
```php
use CodeIgniter\API\ResponseTrait;
use CodeIgniter\RESTful\ResourceController;

class Product extends ResourceController
{
    use ResponseTrait;
    
    public function __construct()
    {
        $this->respond(["status"=>TRUE,"message"=>"Passed"],200);
    } 

    public function index()
    {
        echo 'blablabla';
    }
}
```

**Comment by kenjis** [comment] 2022-08-11 04:04
It is illegal. It won't work.

1. You cannot use `return` in `__construct`. Constructor always returns a new instance of the class.
2. `$this->respond()` uses `$this->response` inside, but `$this->response` is not set in the `__construct()` yet.
    It will be set in `initController()`.

**Comment by suwidadi** [comment] 2022-08-11 04:32
> It is illegal. It won't work.
> 
> 1. You cannot use `return` in `__construct`. Constructor always returns a new instance of the class.
> 2. `$this->respond()` uses `$this->response` inside, but `$this->response` is not set in the `__construct()` yet.
>    It will be set in `initController()`.

well noted.
