### ISSUE TITLE
Bug: Setting session expires parameter via $this->sessionExpiration

### ISSUE THREAD

**Issue by crustamet** [codeigniter4/CodeIgniter4#3543] opened 2020-08-26 16:56 UTC
**Describe the bug**
Before the samesite cookie feature i had ajax calls on same domain, and checked in the ajax the user session if it is logged in only then make the ajax scripts.
After upgrade, i put SameSite cookie for both CSRFSameSite and for cookieSameSite
like this 

	public $cookieSameSite = '';
	public $CSRFSameSite   = '';

Now when i run my website and the ajax needs to be called, the cookie for the session disappears like it is getting removed.
I think is setting to expire just as the ajax was called.

I tried like this also

	public $cookieSameSite = 'None';
	public $CSRFSameSite   = 'None';

And it is still the same.
Before all of this everything was working fine.

**CodeIgniter 4 version**
CI4 Development Latest Version

**Expected behavior, and steps to reproduce if appropriate**
The session must not dissapear.
1. Make a session, put a variable inside.
example.com/login

2. Make an ajax call to another link on your domain like this
example.com/ajax/test

3. Verify session be sure to loading the service::session, you don't even have to check the session here automatically disappears.

**Comment by crustamet** [comment] 2020-08-26 17:10
This is my set cookie header with **None**
Set-Cookie: ci_session=511edf0d6cfe7009b386ffbe8b3526e29aeda852; expires=Fri, 02-Jan-1970 00:00:00 GMT; Max-Age=0; path=/; secure; HttpOnly; SameSite=None

This is my set cookie header with Empty value **""**
Set-Cookie: ci_session=511edf0d6cfe7009b386ffbe8b3526e29aeda852; expires=Fri, 02-Jan-1970 00:00:00 GMT; Max-Age=0; path=/; secure; HttpOnly

Like it puts the expiration date to expire at the next request...

**Comment by crustamet** [comment] 2020-08-26 18:11
I think this is because of HttpOnly flag, that i cannot change from settings because of security reasons.
Like all ajax (xhr) requests now cannot check the session ?

I repeat before the samesite update worked perfectly.

**Comment by michalsn** [comment] 2020-08-26 18:22
I tried to reproduce this issue but so far without luck. Would you be able to provide us with a simple controller class and a view that executes the ajax query? You can share it via [gist](https://gist.github.com/) if you want.

As you mentioned, the problem also occurs when SameSite is not set, so there is a chance that the problem is elsewhere. A simple code that reproduces this issue would be really helpful.

**Comment by crustamet** [comment] 2020-08-26 19:29
**Session Config** 

	public $sessionDriver            = 'CodeIgniter\Session\Handlers\DatabaseHandler';
	public $sessionCookieName        = 'ci_session';
	public $sessionExpiration        = 86400;
	public $sessionSavePath          = 'sessions_admin';
	public $sessionMatchIP           = FALSE;
	public $sessionTimeToUpdate      = 600;
	public $sessionRegenerateDestroy = TRUE; 

	public $cookiePrefix   = 'core_';
	public $cookieDomain   = '';
	public $cookiePath     = '/';
	public $cookieSecure   = true;
	public $cookieHTTPOnly = true;
	public $cookieSameSite = '';

____________________________________________________

**AdminPanel Controller**

	use CodeIgniter\Controller;

	use CodeIgniter\HTTP\RequestInterface;
	use CodeIgniter\HTTP\ResponseInterface;
	use Psr\Log\LoggerInterface;

	use Config\Services;
	use Config\Database;

	public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
	{
		// Do Not Edit This Line
		parent::initController($request, $response, $logger);
		
		$this->db 		= Database::connect();
		$this->session 	= Services::session();
	}

_____________________________

**Dashboard Controller**

	class Dashboard extends AdminPanel
	{
		use \BackEnd\Libraries\Auth\AuthTrait;
				
		public function __construct() 
		{
			$this->restrict(current_url());
		}

		public function index(){.......}
	}

_____________________________

**Ajax Controller**

	use CodeIgniter\Controller;

	use CodeIgniter\HTTP\RequestInterface;
	use CodeIgniter\HTTP\ResponseInterface;
	use Psr\Log\LoggerInterface;

	use Config\Services;
	use Config\Database;

	class Ajax extends Controller
	{
		protected $helpers = ['utility'];
		
		public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
		{
			// Do Not Edit This Line
			parent::initController($request, $response, $logger);
			
			$this->db = Database::connect();		
		}
	}

_____________________________

**Ajax Controller for Dashboard**

	use BackEnd\Controllers\Ajax;
	use Config\Services;

	class Dashboard extends Ajax
	{
		use \BackEnd\Libraries\Auth\AuthTrait;
		
		public function __construct() 
		{
			$this->restrict_ajax(current_url());
		}
		
		public function getServerUsage()
		{
			$stat1 = GetCoreInformation();
			sleep(1);
			$stat2 = GetCoreInformation();
			
			$cpus = GetCpuPercentages($stat1, $stat2);
			
			$count = $return['cpus'] = count($cpus);
			
			$avg = 0;
			foreach($cpus as $cpu) $avg += $cpu['idle'];
			$avg = 100 - round($avg / $count);
			
			$return['load'] = $avg;
			
			$response = Services::response();
			
			$response->setStatusCode(200);
			$response->setHeader('Content-type', 'text/html');
			$response->noCache();

			return $response->setJSON($return);
		}
	}

__________________________________

**AuthTrait for The Ajax Dashboard**

	use Config\Services;
	use CodeIgniter\Router\Exceptions\RedirectException;

	use App\Libraries\Exceptions\ModulesException as ModulesException;

	trait AuthTrait 
	{

		public function restrict_ajax(string $uri=null)
		{
			// return TRUE;
			$this->session = Services::session();
		
			if ($this->session->has('admin'))
			{			
				return true;
			}

      			$this->session->setFlashdata('errors_login', 'unauthorized');
        
        		throw new RedirectException( route_to('login') );
   		}
	}

________________________________________________

The Actual Ajax call javascript

	$(function () {

		var timeOutServerUsage = 0;
		
		var ajaxServerUsage = function () {
			$.ajax({
				url: base_url+'/ajax/getServerUsage',
				headers: {'X-Requested-With': 'XMLHttpRequest'},
			}).done(function(response) {
				$('#cpuUsage').text(response.load+'% '+'('+response.cpus+' CPU`s)');
				$('#cpuUsageProgressBar').css('width', response.load+'%');
				
				timeOutServerUsage = setTimeout(ajaxServerUsage, 5000);
				
			}).fail(function(response){
				console.log(response);
				
				clearTimeout(timeOutServerUsage);
			});
		};
		
		ajaxServerUsage();

	});

**Comment by crustamet** [comment] 2020-08-26 19:33
If this source is not good, i can give you a private share screen maybe on discord or something..

**Comment by crustamet** [comment] 2020-08-26 20:16
Even though i want to use SameSite = Strict.
For sure it must work i am using the ajax calls from the same site anyways same domain same protocol same everything..

**Comment by crustamet** [comment] 2020-08-26 21:03
Yes i found the issue dude.

In File System/Session/Session

Method

	protected function setCookie()
	{
		if (PHP_VERSION_ID < 70300)
		{
			$sameSite = '';
			if ($this->cookieSameSite !== '')
			{
				$sameSite = '; samesite=' . $this->cookieSameSite;
			}

			setcookie(
				$this->sessionCookieName,
				session_id(),
				(empty($this->sessionExpiration) ? 0 : time() + $this->sessionExpiration),
				$this->cookiePath . $sameSite, // Hacky way to set SameSite for PHP 7.2 and earlier
				$this->cookieDomain,
				$this->cookieSecure,
				true
			);
		}
		else
		{
			// PHP 7.3 adds another function signature allowing setting of samesite
			$params = [
				'expires'  => $this->sessionExpiration,
				'path'     => $this->cookiePath,
				'domain'   => $this->cookieDomain,
				'secure'   => $this->cookieSecure,
				'httponly' => true,
			];

			if ($this->cookieSameSite !== '')
			{
				$params['samesite'] = $this->cookieSameSite;
			}
			
			setcookie(
				$this->sessionCookieName,
				session_id(),
				$params
			);
		}
	}


Here on line where the PHP version is bigger 7.3

	$params = [
		'expires'  => $this->sessionExpiration,
		'path'     => $this->cookiePath,
		'domain'   => $this->cookieDomain,
		'secure'   => $this->cookieSecure,
		'httponly' => true,
	];

**The Expires should be time() +  $this->sessionExpiration,**


	$params = [
		'expires'  => time() + $this->sessionExpiration,
		'path'     => $this->cookiePath,
		'domain'   => $this->cookieDomain,
		'secure'   => $this->cookieSecure,
		'httponly' => true,
	];

**Comment by crustamet** [comment] 2020-08-26 21:04
I don't know how you guys didn't saw this before...

**Comment by crustamet** [comment] 2020-08-26 21:12
I am really happy you guys included SameSite

I post long time here on codeigniter 4 github #2374
I waited a long time for this to be implemented. :D

**Comment by michalsn** [comment] 2020-08-27 17:12
Yeah... we missed it and yesterday I was testing your issue on PHP 7.2... 😅 Thanks!

Resolved via #3546

**Closed by michalsn** 2020-08-27 17:12 UTC
Labels: bug
