### ISSUE TITLE
codeigniter composer global installer

### ISSUE THREAD

**Issue by adamkenway007** [codeigniter4/CodeIgniter4#3266] opened 2020-07-11 03:18 UTC
is there any chance add composer's system-wide codeigniter/installer to make installation shorter.

**Comment by ivantcholakov** [comment] 2020-07-13 10:04
https://github.com/codeigniter4/appstarter - are you familiar with this way of installation?

**Comment by paulbalandan** [comment] 2020-07-14 20:52
@adamkenway007, are you referring to something like `laravel/installer`?

**Comment by adamkenway007** [comment] 2020-07-16 14:24
> @adamkenway007, are you referring to something like `laravel/installer`?

yes similiar like that
https://laravel.com/docs/7.x/installation

> Once installed, the laravel new command will create a fresh Laravel installation in the directory you specify. For instance, laravel new blog will create a directory named blog containing a fresh Laravel installation with all of Laravel's dependencies already installed:

**Comment by paulbalandan** [comment] 2020-07-16 17:38
Since this is not a bug, this should be asked in the forum instead: https://forum.codeigniter.com/

As far as I know, there's no plan, or no plan *yet*, for a global installer. I don't know. But since you're asking, you may *try* my [installer](https://paulbalandan/codeigniter4-installer). :)

**Comment by adamkenway007** [comment] 2020-07-17 01:30
> Since this is not a bug, this should be asked in the forum instead: https://forum.codeigniter.com/
> 
> As far as I know, there's no plan, or no plan _yet_, for a global installer. I don't know. But since you're asking, you may _try_ my [installer](https://paulbalandan/codeigniter4-installer). :)

Interesting,this is what i looking for this time.thanks
i hope your codeigniter/installer become official next time and also documented in codeigniter4 userguide

**Comment by paulbalandan** [comment] 2020-07-17 02:26
Thank you for your kind words. 😁

**Comment by adamkenway007** [comment] 2020-07-19 08:08
Can this thread mark as enhancement,please.

**Comment by michalsn** [comment] 2020-08-03 14:28
We don't have plans to include this feature at this moment. Also, there is no volunteer who would like to work on this, so I'm closing this. As always, PRs are welcomed.

**Closed by michalsn** 2020-08-03 14:28 UTC
