### ISSUE TITLE
Bug: php spark migrate on testing environment doesn't work

### ISSUE THREAD

**Issue by lefuentes** [codeigniter4/CodeIgniter4#3309] opened 2020-07-14 23:10 UTC
**Describe the bug**
When I change environment variable CI_ENVIRONMENT to testing, the command `php spark migrate` doesn't work. I want to migrate all migrations files on app/Database/Migrations to test my app. 
It returns that there is an error on routes.

![image](https://user-images.githubusercontent.com/8377820/87484841-a26abc80-c60d-11ea-8242-e5746f2a854f.png)

**CodeIgniter 4 version**
CodeIgniter CLI Tool - Version 4.0.3

**Context**
 - OS: Archlinux
 - PHP version : 7.4.6

**Comment by paulbalandan** [comment] 2020-07-15 16:23
This is confirmed. Tested on `codeigniter4/framework` v4.0.3 and latest `codeigniter4/codeigniter4`. Even running `php spark` yields Error 404.

**Comment by MGatner** [comment] 2020-07-15 20:10
I'm not entirely sure but my guess is that `ENVIRONMENT` set to testing is intended for Unit Tests and Continuous Integration, not running the application manually to test it. If you need an environment to "try out" I would recommend setting `development` as that is pre-configured for such use; alternatively you could define your own, "staging" or something.

**Comment by lefuentes** [comment] 2020-07-15 21:03
@MGatner I understand your point. But I need migrate into testing database to run unit test and integration test. How can I do that without `php spark migrate`? 
I tried it with `php spark migrate -g tests` and `ENVIRONMENT = development `but didn't work.

**Comment by MGatner** [comment] 2020-07-15 21:12
Typically you would do this programmatically, either by specifying the migration namespaces on the Database Test Case (https://codeigniter4.github.io/CodeIgniter4/testing/database.html) or by using MigrationRunner directly in your fixture. 

I recommend checking out the CodeIgniter Playground if you are new to testing in the framework. It has some example test cases, tests, and docs (https://github.com/codeigniter4projects/playground/blob/develop/docs/testing.md) that should be helpful.

**Comment by lonnieezell** [comment] 2020-07-17 19:23
Yes, biggest piece of advice here is don't use the environment "testing". That's the mode set when running phpunit and has special conditions built into the framework at various places to assist with that. For example, when running automated tests it's always running from the CLI and there are a number of times when you want to simulate an HTTP request so that check was placed there. 

I believe @MGatner gave the appropriate steps here so am closing it. If you still run into problems under environments other than `testing` feel free to re-open with additional details.

**Closed by lonnieezell** 2020-07-17 19:23 UTC
Labels: bug
