### ISSUE TITLE
Problem with sessions via redis

### ISSUE THREAD

**Issue by motoroller1983** [codeigniter4/CodeIgniter4#8322] opened 2023-12-11 07:42 UTC
### PHP Version

8.2

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL

### What happened?

Some time i got

ERROR - 15:49:27 10-12-2023 --> Session: Error while trying to free lock for ci_session:ci_session:7aa8677c7de05ba9ad167233d5a2cddfee9e5e2f:lock
ERROR - 14:31:21 10-12-2023 --> Session: Unable to obtain lock for ci_session:ci_session:a489f0c94cb43cba56f6c0a97ef79359c3cf9a47 after 30 attempts, aborting.
ERROR - 14:31:26 10-12-2023 --> Session: Unable to obtain lock for ci_session:ci_session:a489f0c94cb43cba56f6c0a97ef79359c3cf9a47 after 30 attempts, aborting.
ERROR - 15:48:59 10-12-2023 --> Session: Error while trying to free lock for ci_session:ci_session:0f55e709dcae28ebc1b381dd1fe4f7cb07b222f6:lock
ERROR - 17:02:48 10-12-2023 --> Session: Error while trying to free lock for ci_session:ci_session:42d84fae09e8967219b133b14e34a3b292307ecb:lock
ERROR - 17:02:49 10-12-2023 --> Session: Error while trying to free lock for ci_session:ci_session:42d84fae09e8967219b133b14e34a3b292307ecb:lock
ERROR - 18:11:56 10-12-2023 --> Session: Error while trying to free lock for ci_session:ci_session:9e47dfb8f009afa6f7b3e387e3c1a6005134e9d4:lock

### Steps to Reproduce

happens unexpectedly and randomly

### Expected Output

happens unexpectedly and randomly

**Comment by kenjis** [comment] 2023-12-11 09:21
Try #8323
But I did not test this yet. Be careful.

**Comment by kenjis** [comment] 2024-01-20 08:51
Duplicate of #4391
If there is any information, add to #4391

**Closed by kenjis** 2024-01-20 08:51 UTC
Labels: bug, duplicate
