### ISSUE TITLE
Bug: Reverse routing causes error "preg_match(): Compilation failed: missing closing parenthesis"

### ISSUE THREAD

**Issue by dimtrovich** [codeigniter4/CodeIgniter4#7876] opened 2023-08-29 13:02 UTC
### PHP Version

8.1

### CodeIgniter4 Version

4.4.0

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

Unable to generate a URL attached to a route defined with custom placeholders.
An exception is thrown at *SYSTEMPATH\Router\RouteCollection.php at line 1343*

### Steps to Reproduce

- Add custom placeholder
```php 
$routes->addPlaceholder([
    'version' => 'master|\d+\.(?:\d+|x)',
    'page'    => '[a-z0-9-]+',
]);
```
- Create 2 routes for test
```php 
$routes->get('docs/(:version)', function() {
    echo 'Test the documentation';
});
$routes->get('docs/(:version)/(:page)', function() {
    echo 'Test the documentation segment';
}, ['as' => 'docs.version']);

```
- So far everything is ok. Now let's try to get a 2nd route url (docs.version) from the 1st route
```php
$routes->get('docs/(:version)', function() {
    echo 'Test the documentation --- '  . url_to('docs.version', '10.9', 'install');
});
```

at this level it no longer gives. yet if I don't use the `url_to` function, the text displays normally, so I dare to believe that my regex has no error

1st Image: Error when i use `url_to`  function in the 1st route
2nd Image: The 2nd route is displayed normally
3th Image: The 1st route is displayed normally when the `url_to` function is not used

![Error when i use `url_to`  function](https://github.com/codeigniter4/CodeIgniter4/assets/37987162/8ebe5395-09f6-43e2-9064-512ea046d19d)
![the 2nd route is displayed normally](https://github.com/codeigniter4/CodeIgniter4/assets/37987162/d7ccff61-7068-4bce-a751-8d543f7ccd46)
![the 1st route is displayed normally when the `url_to` function is not used](https://github.com/codeigniter4/CodeIgniter4/assets/37987162/6d047ff3-5a73-4899-8a5f-1650f7a41d1f)

### Expected Output

the display of the corresponding url (http://localhost:8000/docs/10.9/install)

### Anything else?

This bug is a continuation of a ticket (feature request) opened on the forum: https://forum.codeigniter.com/showthread.php?tid=88365

**Comment by kenjis** [comment] 2023-08-29 21:20
Thank you for reporting.

This is duplicate of #7237
If you could fix the code, send a PR.

**Comment by kenjis** [comment] 2023-08-29 21:24
The cause seems to be the same, but the error occurs in a different place, so reopen.

**Comment by kenjis** [comment] 2023-08-29 21:26
```
$ php spark routes

CodeIgniter v4.4.0 Command Line Tool - Server Time: 2023-08-29 21:25:57 UTC+00:00

+--------+-------------------------------------------+--------------+------------------------------+----------------+---------------+
| Method | Route                                     | Name         | Handler                      | Before Filters | After Filters |
+--------+-------------------------------------------+--------------+------------------------------+----------------+---------------+
| GET    | /                                         | »            | \App\Controllers\Home::index |                | toolbar       |
| GET    | docs/(master|\d+\.(?:\d+|x))              | »            | (Closure)                    | <unknown>      | <unknown>     |
| GET    | docs/(master|\d+\.(?:\d+|x))/([a-z0-9-]+) | docs.version | (Closure)                    | <unknown>      | <unknown>     |
+--------+-------------------------------------------+--------------+------------------------------+----------------+---------------+
```

**Comment by kenjis** [comment] 2023-08-30 02:20
Try #7880

**Closed** 2023-09-04 20:29 UTC
Labels: bug
