### ISSUE TITLE
Bug: function to redirect()->to() remove query string

### ISSUE THREAD

**Issue by hunter-and1** [codeigniter4/CodeIgniter4#5829] opened 2022-03-24 15:36 UTC
### PHP Version

7.3

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.2

### What happened?

function redirect()->to() remove query builder

### Steps to Reproduce

```php
return redirect()->to('http://localhost/test?y=2022') // he return http://localhost/test
```

### Expected Output

expected redirect to http://localhost/test?y=2022

### Anything else?
i guess probem in functtion setHeader in ResponseTrait.php
_No response_

**Comment by kenjis** [comment] 2022-03-25 08:48
Ref: https://github.com/codeigniter4/CodeIgniter4/pull/1329/commits/ba07b47b181a558a1716b8f790971a70d4e096e2

**Comment by kenjis** [comment] 2022-03-25 08:58
@hunter-and1 
Can't reproduce.

```php
<?php

namespace App\Controllers;

class Home extends BaseController
{
    public function index()
    {
        return redirect()->to('http://localhost:8080/home/test?y=2022');
    }

    public function test()
    {
        return __METHOD__;
    }
}
```
![Screenshot 2022-03-25 17 56 11](https://user-images.githubusercontent.com/87955/160088613-81bfe0ac-4ace-4ab7-b7d8-ff0ba8f6958a.png)

**Comment by hunter-and1** [comment] 2022-03-25 15:07
i think ik problem i use `return redirect()->to($back)->withInput()->with('errors', $this->validator->getErrors());`
and withInput he just create get parramter how i use tthat also

**Comment by kenjis** [comment] 2022-03-26 04:19
I changed to:
```php
return redirect()->to('http://localhost:8080/home/test?y=2022')->withInput();
```
But the result was the same. The redirected URL is `http://localhost:8080/home/test?y=2022`.

**Comment by paulbalandan** [comment] 2022-04-18 12:49
No feedback. Closing.

**Closed by paulbalandan** 2022-04-18 12:49 UTC
Labels: waiting for info
