### ISSUE TITLE
Mysql update , affectedRows return bug

### ISSUE THREAD

**Issue by sundogya** [codeigniter4/CodeIgniter4#2003] opened 2019-05-13 06:06 UTC
In mysql table , i set a unsigned demical(10,2) key(balance).When i update some records 

`mysql>UPDATE `taishan_user` SET `join_lines` = join_lines + 1 , `balance` = balance - 100.00 WHERE `id` = 1;`
`mysql>ERROR 1264 (22003): Out of range value for column 'balance' at row 1`

And when i use mysqli_query($con,$query),then mysqli_affected_rows($con), i get a '-1'.
When i use $this->db->query($sql); then $this->db->affectedRows(), i get a '1'.
Hope you improve this.

**Comment by chistel** [comment] 2019-05-13 18:13
It's not a codeigniter issue. What's the size of the balance column??

**Comment by jim-parry** [comment] 2019-09-17 12:43
@chistel Do you have a reference for the cause of this? Why do you suggest it isn't a CodeIgniter issue?

**Comment by michalsn** [comment] 2019-10-01 16:44
I just tested this and everything seems to be fine. Definitely not a bug.

**Explanation**
By default, CodeIgniter runs all queries without strict mode, so:
```sql
UPDATE taishan_user SET join_lines= join_lines + 1, balance = balance - 100.00 WHERE id = 1
```
will execute just fine. Even if `balance` is out of range (this fact will be ignored and field set to `0`), there is still a `join_lines` field that will be incremented properly. That's why `affecteRows` return `1`.

**Solution**
Turn on `strictOn` in your connection array (`app/Config/Database.php`) to get desired result.

**Comment by lonnieezell** [comment] 2019-10-04 03:04
Sounds like a good explanation and solution from @michalsn. Closing.

**Closed by lonnieezell** 2019-10-04 03:04 UTC
Labels: waiting for info
