### ISSUE TITLE
Bug: spark make:cell doesn't create view file properly

### ISSUE THREAD

**Issue by rcorsari** [codeigniter4/CodeIgniter4#7469] opened 2023-05-01 16:31 UTC
deleted because of a mistake, sorry, I recap in the following reply

**Comment by rcorsari** [comment] 2023-05-01 17:04
Environment WIndows
PHP 8.2
Codeigniter is 4.3.4 installed as appStarter with composer
MariaDB is latest version
Served with php spark serve


This is the terminal
(follows after the terminal output)
```
C:\WWW\htmx>php spark make:cell PippoCell

CodeIgniter v4.3.4 Command Line Tool - Server Time: 2023-05-01 16:56:42 UTC+00:00

File created: APPPATH\Cells\PippoCell.php

File created: APPPATH\Cells\pippo_cell.php
```

but these are the contents of the two files

PippoCell.php
```
<?php

namespace App\Cells;

use CodeIgniter\View\Cells\Cell;

class PippoCell extends Cell
{
    //
}
```

and

pippo_cell.php
```
<?php

namespace App\Cells;

use CodeIgniter\View\Cells\Cell;

class pippo_cell extends Cell
{
    //
}
```

**Comment by kenjis** [comment] 2023-05-02 00:31
Please use bug report template.
And what's your issue?
The behavior you reported is expected.

**Comment by rcorsari** [comment] 2023-05-02 08:16
So now both the cell and the cellview are a class?
Thank you for confirming
I ask because one subversion ago, 4.3.3 the cells bug was just the naming of the files
but the view content was HTML and exactly a DIV opening and closing tag
thank you

**Comment by paulbalandan** [comment] 2023-05-02 08:31
I think this is a bug caused by #7458. The addition of `make:cell` in the `Config/Generators` array effectively bypasses `$this-template` reassignment in https://github.com/codeigniter4/CodeIgniter4/blob/729634c3561e1d8d0742f0e691c810ced8ce6a67/system/Commands/Generators/CellGenerator.php#L96, causing both the class name and view name using the same template.

**Comment by paulbalandan** [comment] 2023-05-02 08:56
Confirmed to be found in v4.3.4, not on v4.3.3

**Comment by kenjis** [comment] 2023-05-02 11:43
Oh, I see. I didn't see the contents of the files.

**Closed** 2023-05-21 01:51 UTC
Labels: bug
