### ISSUE TITLE
Bug: send emails

### ISSUE THREAD

**Issue by DevLogsan** [codeigniter4/CodeIgniter4#6218] opened 2022-07-01 15:18 UTC
### PHP Version

8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.24

### Unable to send mails with Codeigniter 4

I want to send emails with a google email address but now the "Less secure app access" parameter is disabled and impossible to re-enable it.

[https://support.google.com/accounts/answer/6010255?hl=en&authuser=1&visit_id=637922832282988134-2476474830&p=less-secure-apps&rd=1](url)

### Steps to Reproduce

Simply reproduce as the example filling in with it's data.

[https://codeigniter.com/user_guide/libraries/email.html?highlight=send#sending-email](url)

and fill in correctly `app/Config/Email.php`

### Expected Output

no mail sent

**Comment by kenjis** [comment] 2022-07-01 20:34
Duplicate of #6217

**Closed by kenjis** 2022-07-01 20:34 UTC
Labels: duplicate
