### ISSUE TITLE
Bug: File rewrite.php is always lost in large-request unhandled error

### ISSUE THREAD

**Issue by MufidJamaluddin** [codeigniter4/CodeIgniter4#3818] opened 2020-10-26 00:37 UTC
**Describe the bug**
Stress tested the CodeIgniter4 apps with error module, i ran the app with `php spark serve` then `php spark db:seed ...` and executed the stress test, but the system is always remove file rewrite.php in internal modules which isn't able to restore!

**1. Tried in success scenario**

![image](https://user-images.githubusercontent.com/28973632/97123757-cd61c200-175f-11eb-9702-8c51fecd1bad.png)

**2. Hitted error module with large request**

![image](https://user-images.githubusercontent.com/28973632/97123401-4c55fb00-175e-11eb-9074-7e20b8a7306c.png)

**3. File rewrite.php always lost**

![image](https://user-images.githubusercontent.com/28973632/97123388-419b6600-175e-11eb-805e-c0e9c5b7d859.png)

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
All system was affected

**Expected behavior, and steps to reproduce if appropriate**
Error 500 with trace in log

**Context**
 - OS: Windows 10
 - PHP version 7.4.8
 - Composer version 2.0.0

**Comment by otengkwame** [comment] 2020-10-31 00:49
I'm curious and this is an interesting one. What do you think could be the possible reason for a file to be removed when lot's of request come through (to it).

**Comment by paulbalandan** [comment] 2020-11-30 07:03
Perhaps this is caused by your anti-virus program? We have received reports that the AV program deletes the `rewrite.php` marking it as Trojan. There is nothing in the framework that deletes this file and possibly this could be from external sources.

**Closed by paulbalandan** 2020-11-30 07:03 UTC
Labels: bug
