### ISSUE TITLE
Bug: Redirect to route ignores path set in baseurl

### ISSUE THREAD

**Issue by yol** [codeigniter4/CodeIgniter4#2119] opened 2019-08-04 09:52 UTC
**Describe the bug**
When using redirect to route responses in a controller, paths in the configured baseURL are lost.

This is exactly like #1126, but the code has changed since the fix and the cause is now different. I.e., this is a regression.

**CodeIgniter 4 version**
4.0.0-beta4

**Affected module(s)**
router

**Expected behavior, and steps to reproduce if appropriate**
With app.baseURL configured as `http://localhost/path/to/app/` and route configured with `$route->get('myController/test', 'MyController::test')`:

`return redirect()->route('MyController::test')` in a controller
* should redirect to `http://localhost/path/to/app/myController/test`, but
* in fact redirects to `http://localhost/myController/test`.

Initial analysis pertaining to the cause:
* Reverse-resolving the route gives `/myController/test` (with preceding slash)
* `RedirectResponse->route` tries to use `base_url` to wrap the path
* `base_url` uses `URI->resolveRelativeURI` to set the path over the `baseURL`
* this removes all path info from the configured base URL since the route URI begins with `/` and therefore is absolute, completely overriding the path

**Context**
 - OS: Linux
 - Web server lighttpd 1.4.54
 - PHP version 7.3.6

**Comment by pkerling** [comment] 2019-08-04 10:01
Addendum: Actually, it would have to use `site_url` and not `base_url` (such that `index.php` or whatever is configured is also included if needed)

**Comment by lonnieezell** [comment] 2019-08-13 03:43
That's a good catch. Care to submit a PR?

**Comment by pkerling** [comment] 2019-08-15 16:24
To be honest, I'm not sure what the concept behind the URL functions is, i.e., which ones should return paths with `/` and which not, and whether paths beginning with `/` should be taken as absolute or still relative to the URL? So I can cook up a PR but I would definitely need some guidance on how it is supposed to work.

**Comment by lonnieezell** [comment] 2019-08-15 16:45
Resolving relative URI's follows the HTTP specs, so if a '/' is at the beginning of a request it would override any additional segments already there. 

In this case, I think slash should indicate it is relative to `App.basePath`, since that's being used to specify where the site can be found. Any that do not have a leading slash should be relative to the current page.

**Comment by jim-parry** [comment] 2019-10-15 11:26
The PR to fix this is stalled, so removing from rc.3

**Comment by robertotremonti** [comment] 2019-11-25 14:59
The bug is also in `$pager->getPageURI()` method.

**Comment by lonnieezell** [comment] 2019-11-25 15:11
@robertotremonti Have you tested this with the latest develop branch, or just rc-3? We've had some URL fixes go into place a week or two ago.

**Comment by robertotremonti** [comment] 2019-11-25 15:43
@lonnieezell I'm using latest 4.0.0-rc.3 release.

**Comment by robertotremonti** [comment] 2019-11-25 15:46
@lonnieezell Anyway I've just tried a quick test by replacing `system` folder from latest develop branch and the bug doesn't seem to be fixed.

**Comment by walaman** [comment] 2019-11-26 07:01
Looks like `current_url` have the same issue

**Comment by robertotremonti** [comment] 2019-11-26 10:16
All function handling URLs `(current_url()`, `previous_url()`, ...) have the same problem.
I've just tried latest `develop` branch but the problem has not been fixed yet.

**Comment by robertotremonti** [comment] 2019-12-10 15:35
In addition, I report that `base_url('/admin/login')` doesn't take into consideration `$indexPage` value.

For example `http://localhost/admin/login` is not the same as `http://localhost/index.php/admin/login` when `MOD_REWRITE` is not set.

**Comment by lonnieezell** [comment] 2019-12-16 03:37
> In addition, I report that base_url('/admin/login') doesn't take into consideration $indexPage value.

That's correct, and by design. If you need `$indexPage` taken into account, use `site_url()`.

**Comment by lavilaso** [comment] 2020-01-20 04:49
I have exactly the same problem, my application is broken at this time because of this. Is there any progress on this?

@lonnieezell What would I have to do to try your solution to this problem?

**Comment by lavilaso** [comment] 2020-01-20 05:06
@lonnieezell Your commit solves the problem. Thanks!

**Closed** 2020-01-22 15:09 UTC
Labels: bug
