### ISSUE TITLE
Bug: FILTER_SANITIZE_STRING is deprecated (PHP 8.1.0 early test)

### ISSUE THREAD

**Issue by sys4soft** [codeigniter4/CodeIgniter4#4938] opened 2021-07-16 22:59 UTC
Hi there.

I'm currently testing a **PHP 8.1.0 master branch Windows compilation**, which will certainly be very close to the final version of PHP 8.1.0, and **CodeIgniter 4.1.3**.

In the development environment, this error is coming up:

`SYSTEMPATH\Router\RouteCollection.php at line 1368`
`line: 1368         $from = filter_var($prefix . $from, FILTER_SANITIZE_STRING);`
`ErrorException: Constant FILTER_SANITIZE_STRING is deprecated`

It seems to me that this would be a good time to prepare for the future by fixing this "future" bug that is coming.

I will not post any "future bugs" here again unless you expressly direct me to do so, as it may not be a priority at this time to focus on the solution.

Let me know if you want me to identify potential "future bugs" as I test with unreleased versions of PHP.

Specs:
Using Laragon (Apache 2.4.35 + PHP 8.1.0 master branch compilation)

**Comment by paulbalandan** [comment] 2021-07-17 12:57
Hi, thanks for early testing. Please direct all found issues under #4883 so we can consolidate all issues. I'll close this first as this is not a bug but a compat issue. Thanks anyway.

**Closed by paulbalandan** 2021-07-17 12:57 UTC
Labels: bug
