### ISSUE TITLE
Bug: Parse error: syntax error, unexpected '_592_000' (T_STRING), expecting ')'

### ISSUE THREAD

**Issue by fre2mansur** [codeigniter4/CodeIgniter4#6305] opened 2022-07-28 01:03 UTC
### PHP Version

7.3

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### What happened?

Parse error: syntax error, unexpected '_592_000' (T_STRING), expecting ')' in E:\MYPROJECTS\codignitor\app\Config\Constants.php on line 41

### Steps to Reproduce

php spark serve

### Expected Output

This will launch the server and you can now view your application in your browser at http://localhost:8080/.

### Anything else?

Im using VS CODE editor

**Comment by iRedds** [comment] 2022-07-28 01:10
CI 4.2+ requires php version 7.4+

**Comment by kenjis** [comment] 2022-07-28 01:40
Duplicate of #6306

**Closed by kenjis** 2022-07-28 01:40 UTC
Labels: duplicate
