### ISSUE TITLE
Bug: migration error Class 'Locale' not found

### ISSUE THREAD

**Issue by smartyoon** [codeigniter4/CodeIgniter4#6557] opened 2022-09-20 20:23 UTC
### PHP Version

7.4, 8.0, 8.1

### CodeIgniter4 Version

4.2.6

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

fpm-fcgi

### Database

mysql8

### What happened?

When I enter the migration command, I get an error.

Class 'Locale' not found

at SYSTEMPATH/CodeIgniter.php:181

Backtrace:
  1    ROOTPATH/spark:83
       CodeIgniter\CodeIgniter()->initialize()

### Steps to Reproduce

php spark migration status 

### Expected Output

[Error]

Class 'Locale' not found

at SYSTEMPATH/CodeIgniter.php:181

Backtrace:
  1    ROOTPATH/spark:83
       CodeIgniter\CodeIgniter()->initialize()

**Comment by kenjis** [comment] 2022-09-20 22:53
Duplicate of #4775, #3294
See https://codeigniter4.github.io/CodeIgniter4/intro/requirements.html#server-requirements

**Comment by smartyoon** [comment] 2022-09-21 03:27
The module installation is already complete. 
Installed to suit the conditions.

**Comment by kenjis** [comment] 2022-09-21 05:17
@smartyoon How did you get the info?

**Comment by smartyoon** [comment] 2022-09-21 05:41
@kenjis info from php74 -m

**Comment by kenjis** [comment] 2022-09-21 05:55
@smartyoon No, no. My question is: How did you get the output?

**Comment by kenjis** [comment] 2022-09-21 05:56
Try:
```
$ php74 spark migrate status
```

**Comment by smartyoon** [comment] 2022-09-21 06:08
@kenjis You are a genius!! Thanks!

**Comment by kenjis** [comment] 2022-09-21 06:35
As you know, at least you have two php commands, `php` and `php74`.
And these are not the same.

**Closed by kenjis** 2022-09-21 06:35 UTC
Labels: duplicate
