### ISSUE TITLE
Bug: onlyDeleted() conflicts to paginate()

### ISSUE THREAD

**Issue by Hiroki97** [codeigniter4/CodeIgniter4#3482] opened 2020-08-12 04:13 UTC
**Direction**
We use github issues to track bugs, not for support.  
If you have a support question, or a feature request, raise these as threads on our
[forum](https://forum.codeigniter.com/index.php).

**Describe the bug**
I used onlyDeleted() with paginate() and it showed this SQL query from CI4 logger.
![Screenshot (222)](https://user-images.githubusercontent.com/41558998/89973399-cebc3c00-dc92-11ea-9d84-35c439449636.png)

Heres the getResult() and this works. 
![Screenshot (223)](https://user-images.githubusercontent.com/41558998/89973784-cb758000-dc93-11ea-99c7-4fbe543b071d.png)

My situation now.
![Screenshot (224)](https://user-images.githubusercontent.com/41558998/89974195-f57b7200-dc94-11ea-95c2-97eb33ca6d31.png)

**CodeIgniter 4 version**
Codeigniter 4.0.3

**Expected behavior, and steps to reproduce if appropriate**
This should not be conflicted on softDelete and paginate

**Comment by michalsn** [comment] 2020-08-15 16:59
I couldn't reproduce this error with a simple example. Please update your CodeIgniter to 4.0.4 and try again. You can also try to reproduce this error with a simpler query - it would help a lot.

I'm closing this, since it seems more like an issue in your code logic (or outdated CI version), but feel free to continue conversation.

**Closed by michalsn** 2020-08-15 16:59 UTC
Labels: bug
