### ISSUE TITLE
Bug: Session error: session_start(): Failed to read session data

### ISSUE THREAD

**Issue by ChibuezeAgwuDennis** [codeigniter4/CodeIgniter4#5313] opened 2021-11-11 17:51 UTC
### PHP Version

8.1

### CodeIgniter4 Version

4.1.4, 4.1.5

### Which operating systems have you tested for this bug?

~~Linux~~ Android 11

### Which server did you use?

apache

### Database

Mysql 5.6

### What happened?

Codeigniter is return back 
<br>

Here is the error log

```log

ERROR - 2021-11-11 11:20:13 --> Session: Unable to obtain lock for file '/storage/emulated/0/htdocs/speradupgrade/writable/session/ci_session0e542cccc8f7967f6690d9c76fbf6fc008995fbb'.
CRITICAL - 2021-11-11 11:20:13 --> session_start(): Failed to read session data: user (path: /storage/emulated/0/htdocs/speradupgrade/writable/session)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'session_start()...', '/storage/emulat...', 894, Array)
#1 /storage/emulated/0/htdocs/speradupgrade/system/Session/Session.php(894): session_start()
#2 /storage/emulated/0/htdocs/speradupgrade/system/Session/Session.php(238): CodeIgniter\Session\Session->startSession()
#3 /storage/emulated/0/htdocs/speradupgrade/system/Config/Services.php(577): CodeIgniter\Session\Session->start()
#4 /storage/emulated/0/htdocs/speradupgrade/system/Config/BaseService.php(248): CodeIgniter\Config\Services::session(Object(Config\App), false)
#5 /storage/emulated/0/htdocs/speradupgrade/system/Config/BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#6 /storage/emulated/0/htdocs/speradupgrade/system/Config/Services.php(563): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /storage/emulated/0/htdocs/speradupgrade/system/Config/BaseService.php(248): CodeIgniter\Config\Services::session()
#8 /storage/emulated/0/htdocs/speradupgrade/system/Common.php(909): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /storage/emulated/0/htdocs/speradupgrade/app/Controllers/Home.php(9): session()
#10 /storage/emulated/0/htdocs/speradupgrade/system/CodeIgniter.php(824): App\Controllers\Home->index()
#11 /storage/emulated/0/htdocs/speradupgrade/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#12 /storage/emulated/0/htdocs/speradupgrade/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /storage/emulated/0/htdocs/speradupgrade/public/index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
```

> ErrorException
session_start(): Failed to read session data: user (path: /storage/emulated/0/htdocs/speradupgrade/writable/session

This happened as i was developing with my phone on android version 11
Please can anyone check this. I try this on the two version of codeigniter

Here is the screenshot
![Screenshot_20211111-182626](https://user-images.githubusercontent.com/53615067/141345115-e2cba681-cac0-409b-824a-0554260de238.png)

When i checked the session folder the session file was created but no data was actually stored in it.

![Screenshot_20211111-185714](https://user-images.githubusercontent.com/53615067/141346289-318bbba4-c814-4640-b06a-7f7dbd29a05a.png)

![Screenshot_20211111-185903](https://user-images.githubusercontent.com/53615067/141346542-126c1468-636a-4802-ab4a-de525bd61e2d.png)

### Steps to Reproduce

```php

session()->get('username');
```

### Expected Output

I wanted to return back the session username

**Comment by kenjis** [comment] 2021-11-12 02:41
@ChibuezeAgwuDennis 
Can't reproduce. The error seems to be specific to your environment.

And CI4 does not suppor PHP 8.1 yet.

Please ask your support questions in the forums. Thanks! 
https://forum.codeigniter.com/forum-30.html

**Comment by ChibuezeAgwuDennis** [comment] 2021-11-12 07:03
@kenjis 
This was actually working before.
I retry it with PHP >= 7.3.
But still display the same thing.
The session file is actually creating but empty

**Comment by kenjis** [comment] 2021-11-12 07:24
What did you change?

What versions of PHP, CI4 when it was working?

**Comment by ChibuezeAgwuDennis** [comment] 2021-11-12 10:22
@kenjis 
it was on php 7.4

**Comment by truelineinfotech** [comment] 2021-11-12 10:52
Can you check file permissions and phpinfo?

**Comment by truelineinfotech** [comment] 2021-11-12 10:53
Session file shows 0kb. Means problem in file write issue

**Comment by ChibuezeAgwuDennis** [comment] 2021-11-12 11:13
Here is the phpinfo on session

![Screenshot_20211112-121111](https://user-images.githubusercontent.com/53615067/141458145-60697c70-697d-4737-97d1-788c02eea979.png)

**Comment by kenjis** [comment] 2021-11-12 11:37
Are you running CodeIgniter4 on Android 11?
How do you install PHP/Apache?

**Comment by ChibuezeAgwuDennis** [comment] 2021-11-12 17:29
@kenjis 

You can install PHP and Apache and and other development dependencies by using termux apk
Or better still install ksweb server apk to serve for your php and apache

**Comment by kenjis** [comment] 2021-11-13 00:36
> This was actually working before.

Can you show how to build the environment that worked CI4?

And what's has been changed when this error occurs?

If you show steps to reproduce, someone may check the error.
I don't have Android 11.

**Comment by ChibuezeAgwuDennis** [comment] 2021-11-14 04:36
@kenjis 
it was on CI4 version 4.0.4

**Comment by ChibuezeAgwuDennis** [comment] 2021-11-15 10:42
@kenjis 

Here is the error

```log
ERROR - 2021-11-11 11:20:13 --> Session: Unable to obtain lock for file '/storage/emulated/0/htdocs/speradupgrade/writable/session/ci_session0e542cccc8f7967f6690d9c76fbf6fc008995fbb'.
CRITICAL - 2021-11-11 11:20:13 --> session_start(): Failed to read session data: user (path: /storage/emulated/0/htdocs/speradupgrade/writable/session)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'session_start()...', '/storage/emulat...', 894, Array)
#1 /storage/emulated/0/htdocs/speradupgrade/system/Session/Session.php(894): session_start()
#2 /storage/emulated/0/htdocs/speradupgrade/system/Session/Session.php(238): CodeIgniter\Session\Session->startSession()
#3 /storage/emulated/0/htdocs/speradupgrade/system/Config/Services.php(577): CodeIgniter\Session\Session->start()
#4 /storage/emulated/0/htdocs/speradupgrade/system/Config/BaseService.php(248): CodeIgniter\Config\Services::session(Object(Config\App), false)
#5 /storage/emulated/0/htdocs/speradupgrade/system/Config/BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#6 /storage/emulated/0/htdocs/speradupgrade/system/Config/Services.php(563): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 /storage/emulated/0/htdocs/speradupgrade/system/Config/BaseService.php(248): CodeIgniter\Config\Services::session()
#8 /storage/emulated/0/htdocs/speradupgrade/system/Common.php(909): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 /storage/emulated/0/htdocs/speradupgrade/app/Controllers/Home.php(9): session()
#10 /storage/emulated/0/htdocs/speradupgrade/system/CodeIgniter.php(824): App\Controllers\Home->index()
#11 /storage/emulated/0/htdocs/speradupgrade/system/CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#12 /storage/emulated/0/htdocs/speradupgrade/system/CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /storage/emulated/0/htdocs/speradupgrade/public/index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
```

**Comment by kenjis** [comment] 2021-11-15 10:57
> Session: Unable to obtain lock for file '/storage/emulated/0/htdocs/speradupgrade/writable/session/ci_session0e542cccc8f7967f6690d9c76fbf6fc008995fbb'.

It is from here:
https://github.com/codeigniter4/CodeIgniter4/blob/054ce954148de32f990cb26c00ead9f0bbdd5d17/system/Session/Handlers/FileHandler.php#L135-L141

It seems it can't get `LOCK_EX` in your file system.

**Comment by ChibuezeAgwuDennis** [comment] 2021-11-15 11:39
> > Session: Unable to obtain lock for file '/storage/emulated/0/htdocs/speradupgrade/writable/session/ci_session0e542cccc8f7967f6690d9c76fbf6fc008995fbb'.
> 
> It is from here:
> 
> https://github.com/codeigniter4/CodeIgniter4/blob/054ce954148de32f990cb26c00ead9f0bbdd5d17/system/Session/Handlers/FileHandler.php#L135-L141
> 
> It seems it can't get `LOCK_EX` in your file system.

Yes i checked on that before. Trying to see how i can bypass it. So i just drag your attention towards this if anything cab done. Although i would have like to work on this but the not with my pc.

**Comment by kenjis** [comment] 2022-05-26 01:49
This is because of the filesystem, not a CI4 Session bug.
To use Session FileHandler, we need filesystems that can use `flock()`.

Closing.

**Closed by kenjis** 2022-05-26 01:49 UTC
