### ISSUE TITLE
Bug: model() function behavior with classes that has same short name

### ISSUE THREAD

**Issue by WCrash7** [codeigniter4/CodeIgniter4#7710] opened 2023-07-15 10:49 UTC
### PHP Version

8.2

### CodeIgniter4 Version

4.3.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### What happened?

model() function returns same class when passing classes with different namespace and similar short name.

### Steps to Reproduce

Store "LicenseModel ":
```php

namespace App\Models\Store;

use App\Models\BaseModel;

class LicenseModel extends BaseModel
{

}
```

User "LicenseModel ":

```php

namespace App\Models\User;

use App\Models\BaseModel;

class LicenseModel extends BaseModel{

}
```

Test:
```php
namespace App\Controllers\User;

use App\Controllers\BaseController;
use App\Models\Store\LicenseModel as StoreLicense;
use App\Models\User\LicenseModel as UserLicense;

class UserAuth extends BaseController{
	public function login()
	{
		echo "Store Model: " . model(StoreLicense::class)::class ."\n";
		echo "User  Model: " . model(UserLicense::class)::class;
		//return $this->customRender(view("pages/login"));
	}
}
```
Result:
Store Model: App\Models\Store\LicenseModel
User  Model: App\Models\Store\LicenseModel

### Expected Output

Store Model: App\Models\Store\LicenseModel
User  Model: App\Models\User\LicenseModel

**Comment by neznaika0** [comment] 2023-07-15 11:30
Use options as temporary fix
`model(UserLicense::class, false);`

**Comment by kenjis** [comment] 2023-07-16 06:43
Duplicate of #7694

If you have opinion, please post in #7694.

**Closed** 2023-07-16 07:14 UTC
Labels: bug

**Comment by kenjis** [comment] 2023-07-16 07:33
Dose `model(UserLicense::class, false)` work?

Try:
```php
model('User/LicenseModel');
```

**Comment by WCrash7** [comment] 2023-07-16 14:08
> Dose `model(UserLicense::class, false)` work?
> 
> Try:
> 
> ```
> model('User/LicenseModel');
> ```

Yes, They both work as temporary fixes
