### ISSUE TITLE
Testing: Easy File upload testing

### ISSUE THREAD

**Issue by lonnieezell** [codeigniter4/CodeIgniter4#8209] opened 2023-11-14 05:55 UTC
We currently don't have a great way to test file uploads for end users. 

It would be nice to be able to simply provide a `CodeIgniter\Files\UploadedFile` object to the request and have it recognize it correctly, set the `enctype` header, and just work...

**Comment by kenjis** [comment] 2023-11-14 07:28
Duplicate of #7987

**Closed by kenjis** 2023-11-14 07:28 UTC
Labels: enhancement
