### ISSUE TITLE
Bug: Spark Serve error

### ISSUE THREAD

**Issue by jolupa** [codeigniter4/CodeIgniter4#6409] opened 2022-08-22 09:50 UTC
### PHP Version

8.1

### CodeIgniter4 Version

4.2.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

sqlite

### What happened?

Just uupgrade to 4.2.4 and when I try to run the local server on CLI  just this error shows.
`[Error]

Call to undefined method CodeIgniter\HTTP\CLIRequest::getGet()

at SYSTEMPATH/Debug/Toolbar.php:452

Backtrace:
  1    APPPATH/Config/Events.php:52
       CodeIgniter\Debug\Toolbar()->respond()

  2    SYSTEMPATH/Events/Events.php:149
       CodeIgniter\Events\Events::Config\{closure}()

  3    SYSTEMPATH/CodeIgniter.php:317
       CodeIgniter\Events\Events::trigger()

  4    SYSTEMPATH/CLI/Console.php:48
       CodeIgniter\CodeIgniter()->run()

  5    ROOTPATH/spark:86
       CodeIgniter\CLI\Console()->run()`

### Steps to Reproduce

`php spark serve`

### Expected Output

The internal php server running on local

### Anything else?

Just in 4.2.4 don't have any problem running on 4.2.3 or 4.2.2

**Comment by kenjis** [comment] 2022-08-22 10:27
Duplicate of #6365

**Comment by kenjis** [comment] 2022-08-22 10:29
Can you show Config/Events.php ?

**Comment by kenjis** [comment] 2022-08-27 12:22
I merged #6421 into `develop` branch.
Please try the latest `develop` branch if you can.

If you still have the error, feel free to reopen.

**Closed by kenjis** 2022-08-27 12:22 UTC
Labels: duplicate
