### ISSUE TITLE
Bug: Argument 1 passed to CodeIgniter\Database\BaseResult::getFirstRow() must be of the type string, null given, called in /system/Model.php on line 383

### ISSUE THREAD

**Issue by 25hweb** [codeigniter4/CodeIgniter4#2877] opened 2020-04-24 14:52 UTC
Hi,
In my model I am trying to get an item by its ID. My code is given bellow:
$id = 5;
$currentUser = new User($id);

I obtain:
Argument 1 passed to CodeIgniter\Database\BaseResult::getFirstRow() must be of the type string, null given, called in /system/Model.php on line 383

CodeIgniter 4.0.2
 - OS: linux
 - Apache 2.4.41  
- PHP Version 7.3.9

**Comment by samsonasik** [comment] 2020-04-24 15:55
please provide complete reproducible example.

**Comment by FelipeAzambuja** [comment] 2020-05-01 01:02
you send a null on variable $id

**Comment by lonnieezell** [comment] 2020-05-01 03:21
Is User a Model or an Entity?

Either way you have the syntax wrong. If it's a Model, the first parameter would be a database connection. If an Entity, it would require an array of fields, not just an $id var. 

Not a bug. Closing. If you need more assistance please ask on the forums.

**Closed by lonnieezell** 2020-05-01 03:21 UTC
Labels: bug

**Comment by abhishekjnvk** [comment] 2021-08-29 18:36
remove  __construct() function from Modal class.

**Comment by rpuig** [comment] 2024-07-30 14:11
why do we need to remove the construct from models?
