### ISSUE TITLE
only_full_group_by - mysqli_sql_exception #1055 - MySql 5.7.24

### ISSUE THREAD

**Issue by perspolise** [codeigniter4/CodeIgniter4#3795] opened 2020-10-22 07:45 UTC
I work with CI version `4.0.2` and `MySql 5.7.24`: 

```
    public function getProducts(int $id = null, $manufacturer = null, $size = null)
    {
        $builder = $this->db->table('product_categories pc');
        $builder->select('p.id, p.name, p.slug, p.manufacturer_id, p.size size, pm.name manufacturer_name, pp.old_price , pp.new_price, pp.created_at');
        $builder->join('products p', 'p.id = pc.product_id');
        $builder->join('product_manufacturers pm', 'p.manufacturer_id = pm.id');
        $builder->join('product_prices pp', 'p.id = pp.product_id');
        $builder->where('pc.category_id', $id);
        $builder->whereIn('p.manufacturer_id', $manufacturer);
        $builder->whereIn('p.size', $size);
        $builder->groupBy('pp.product_id');  //problem is here
        $query = $builder->get()->getResult();
        return $query;
    }

```

error is:

```
Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ci4.pp.old_price' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

I know, I can fix this problem with disable `sql_mode=only_full_group_by` but, I think this method isn't good.

**Comment by michalsn** [comment] 2020-10-22 19:22
I don't really see an issue here. How would you like to deal with it?

I'm closing this since it's not a bug, but feel free to continue the conversation.

**Closed by michalsn** 2020-10-22 19:22 UTC

**Comment by perspolise** [comment] 2020-10-22 21:19
@michalsn @lonnieezell 
![mysqli_sql_exception](https://user-images.githubusercontent.com/19752074/96931041-89ee2600-14c9-11eb-8d72-58815b37622f.png)

**Comment by michalsn** [comment] 2020-10-23 04:57
@perspolise This is a MySQL error (not CodeIgniter) and you already pointed out how to fix it - you should update your configuration. Could you elaborate on what is your idea to handle it better?

**Comment by perspolise** [comment] 2020-10-23 07:56
@michalsn : In MySql `5.7.24`  `sql_mode=only_full_group_by` is enable in default configuration and for fix this problem we need edit configuration(disable it).

![3](https://user-images.githubusercontent.com/19752074/96971841-8dfa6200-1522-11eb-9ac3-5f6733077f1b.png)

**Comment by michalsn** [comment] 2020-10-23 14:25
@perspolise There are no changes since CI3 when it comes to handling this and personally I don't feel that adding some sort of support for this right now would be a good idea. If you really can't work around it I would suggest using `post_controller_constructor` event to change `sql_mode` for a given session, something like this:
```php
Events::on('post_controller_constructor', function() {
	db_connect()->simpleQuery("SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))");
});
```
