### ISSUE TITLE
Cant replace default data form_helpers

### ISSUE THREAD

**Issue by totoprayogo1916** [codeigniter4/CodeIgniter4#4439] opened 2021-03-16 14:07 UTC
**Direction**
```php
form_button('', 'submit', ['type' => 'submit']);
// expected: <button type="submit">submit</button>
// returned: <button type="button" type="submit">submit</button>
```

**Describe the bug**
Cant replace default `type` of form when using extra data.
Also in all of Form Helpers.

**CodeIgniter 4 version** 
4.1.1

**Comment by paulbalandan** [comment] 2021-03-17 13:08
`type` is supplied via the `$data` param, not the `$extra`

**Comment by totoprayogo1916** [comment] 2021-03-19 06:30
> `type` is supplied via the `$data` param, not the `$extra`

I know,
So, we don't have the option to change the default data via `$extra`?

**Comment by paulbalandan** [comment] 2021-03-19 09:13
In that case, this is not a bug an enhancement. Please send a PR if you can.

**Comment by sfadschm** [comment] 2021-03-19 18:43
Is there a specific use case for this? Why not pass the type via `$data?`

**Comment by totoprayogo1916** [comment] 2021-03-20 05:17
with `$data` it may be a habit, without the need to add other attributes such as the second, third and maybe fourth parameters.
but the case is
if `$data` is only used as 'form name', and the second parameter is 'value'
then in the third parameter (`$extra`) because you can input an array and maybe its function is the same as `$data`, then it's not wrong right?

**Comment by paulbalandan** [comment] 2021-05-01 17:36
I don't see a PR incoming for this.
Closing for now, as this is a feature request.

**Closed by paulbalandan** 2021-05-01 17:36 UTC
Labels: enhancement
