### ISSUE TITLE
Bug: php spark Call to undefined function CodeIgniter\Autoloader\get_filenames()

### ISSUE THREAD

**Issue by waga** [codeigniter4/CodeIgniter4#2439] opened 2019-12-05 07:13 UTC
**Describe the bug**
Running command in Linux terminal
`php spark`

cause this message:
> CodeIgniter CLI Tool - Version 4.0.0-rc.3 - Server-Time: 2019-12-05 08:47:31am
> 
> An uncaught Exception was encountered
> 
> Type:        Error
> Message:     Call to undefined function CodeIgniter\Autoloader\get_filenames()
> Filename:    /home/[additional-path]/public_html/system/Autoloader/FileLocator.php
> Line Number: 377

**CodeIgniter 4 version**
4.0.0-rc.3

**Expected behavior, and steps to reproduce if appropriate**
Running command in Windows cause no errors

**Context**
`cat /etc/lsb-release`
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=16.04
> DISTRIB_CODENAME=xenial
> DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

`php -v`
> PHP 7.3.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:31:26) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.3.3-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by 
 Zend Technologies

**Suggestion**
Looking in system/Common.php inside helper function, 
at line 621 
>  $path = $loader->locateFile($filename, 'Helpers');

and 635
> $paths = $loader->search('Helpers/' . $filename);

"Helpers" path with uppercase, but in file system folder is lowercased "helpers", 
linux is case sensitive so fast fix could be replace
'Helpers' with 'helpers' and 'Helpres/' with 'helpers/' (that work for me)
or to change directory.

**Comment by MGatner** [comment] 2019-12-06 14:22
That's definitely an issue with the Filesystem Helper not being loaded. Can you provide the full stack trace so we can make sure the issue is locating the helper?

Aside, the folder in `system` should actually be uppercase: [system/Helpers](https://github.com/codeigniter4/CodeIgniter4/tree/develop/system/Helpers) so if that is the root issue then this might be a problem with your installation.

**Comment by waga** [comment] 2019-12-09 07:10
Hello there.

I checked again the issue and found that problem is in my box :)
I dont find bug with CI4.
Accept my apologize.

Well, the issue with my paths was because i have installed CI3 in git and later
replace files with CI4 wich caused this path mismatch.

**Comment by lonnieezell** [comment] 2019-12-09 14:47
No worries! Glad you found the solution and thanks for letting us know. 

I'll go ahead and close it.

**Closed by lonnieezell** 2019-12-09 14:47 UTC
Labels: bug
