### ISSUE TITLE
Bug: Many redirects when "forceGlobalSecureRequests" is enabled

### ISSUE THREAD

**Issue by TonnyHack** [codeigniter4/CodeIgniter4#5805] opened 2022-03-16 08:46 UTC
### PHP Version

7.4

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB 10.3.27

### What happened?

Many redirects when "forceGlobalSecureRequests" is enabled, and you are in the "testing" environment.
In the other environment it does not cause the same inconvenience using the same configuration and the same files

### Steps to Reproduce

the bug occurs in the system file "common.php" in the function "force_https()"

### Expected Output

fix the bug and release an update

### Anything else?

I solved the problem by removing the "$_SERVER['HTTPS'] === 'test'" method and loading the normal application as before

**Comment by kenjis** [comment] 2022-03-16 09:08
@TonnyHack Thank you for taking time.

> the bug occurs in the system file "common.php" in the function "force_https()"

This is not Steps to Reproduce.
We can't reproduce it.

**Comment by paulbalandan** [comment] 2022-03-16 09:23
"testing" is an internal environment used only for PHPUnit testing. This should not be used by users.

**Comment by paulbalandan** [comment] 2022-04-18 12:47
No feedback. Closing.

**Closed by paulbalandan** 2022-04-18 12:47 UTC
Labels: waiting for info
