### ISSUE TITLE
Bug: Controlled Cells CLI command generates wrong filenames

### ISSUE THREAD

**Issue by sanchawebo** [codeigniter4/CodeIgniter4#7455] opened 2023-04-26 12:08 UTC
### PHP Version

8.2

### CodeIgniter4 Version

4.3.1, 4.3.2, 4.3.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL 5.7.39

### What happened?

When generating a controlled cell via the `php spark make:cell MyCell`-command and echoing it into a site via `<?= view_cell('MyCell') ?>` CodeIgniter generates the following error:
`include(/USERDIR/test_ci4-news/app/Cells/my.php): Failed to open stream: No such file or directory`
The generated filenames are:
- MyCell.php
- my_cell.php

### Steps to Reproduce

- Install CI4 with composer
- Generate a view_cell with the CLI command
- Echo it inside `welcome_message.php` with `<?= view_cell('MyCell') ?>`

### Expected Output

It should print out the following HTML-code:
```html
<div>
    <h1>Cell works!</h1>
</div>
```

### Anything else?

Followed the instructions at: https://codeigniter4.github.io/userguide/outgoing/view_cells.html#controlled-cells

### Workaround/Functioning Code
If you rename the cell's viewfile to `my.php`, alas removing the '_cell' part, it works as expected

**Comment by kenjis** [comment] 2023-04-26 22:54
Duplicate of #7391

**Comment by kenjis** [comment] 2023-04-26 22:57
Thanks for taking the time to fill out this bug report!

Before you begin, **please ensure that there are no existing issues,
whether still open or closed, related to your report**.
If there is, your report will be closed promptly.

For example, if you get the error on View Cells,
you can search the GitHub repository with the keyword "[view cells](https://github.com/search?q=repo%3Acodeigniter4%2FCodeIgniter4+view+cells&type=issues)".

**Closed by kenjis** 2023-04-26 22:57 UTC
Labels: duplicate

**Comment by sanchawebo** [comment] 2023-04-27 06:29
Thanks for your reply but there were no _open_ issues at the time and the linked issue is marked as closed but the bug still persists.

**Comment by kenjis** [comment] 2023-04-27 07:45
It was closed by #7392 and #7392 was merged into `develop` branch.
Try to develop branch.
