### ISSUE TITLE
Not display error

### ISSUE THREAD

**Issue by MonkeyTiger** [codeigniter4/CodeIgniter4#5337] opened 2021-11-16 10:43 UTC
### PHP Version

7.3

### CodeIgniter4 Version

4.1.4

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

cli

### Database

MariaDB 10.4.10

### What happened?

I'm using codeigniter as api server and using postman to test.
If error occurrence in backend, it make log file in logs directory on the server but not return error to the frontend like postman. So I must check log files at each time. How to implement error reporting in http response?

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/65575540/141970574-e1cd3a28-47a3-40d0-8671-e058bf432d6f.png)

### Expected Output

If error occurrence in backend, I want to return error to the frontend.

**Comment by kenjis** [comment] 2021-11-16 12:39
Can't reproduce it.
<img width="991" alt="Screenshot 2021-11-16 21 37 17" src="https://user-images.githubusercontent.com/87955/141986537-f6aea6e2-05c7-4abf-8a32-6cdfa76cd092.png">

**Comment by paulbalandan** [comment] 2021-12-23 06:16
No feedback received. Closing..

**Closed by paulbalandan** 2021-12-23 06:16 UTC
