### ISSUE TITLE
Bug: PHPStan: Error: Call to an undefined method CodeIgniter\Database\BaseBuilder after merged with #4480

### ISSUE THREAD

**Issue by hurtsky** [codeigniter4/CodeIgniter4#4528] opened 2021-04-08 08:01 UTC
**Describe the bug**
after merged with https://github.com/codeigniter4/CodeIgniter4/pull/4480 i got this error in phpstan, and revert it for now is the solution

```
Error: Call to an undefined method CodeIgniter\Database\BaseBuilder::first().
Error: Call to an undefined method CodeIgniter\Database\BaseBuilder::first().
Error: Call to an undefined method CodeIgniter\Database\BaseBuilder::first().
Error: Call to an undefined method CodeIgniter\Database\BaseBuilder::findAll().
Error: Call to an undefined method CodeIgniter\Database\BaseBuilder::findAll().
Error: Call to an undefined method CodeIgniter\Database\BaseBuilder::findAll().
Error: Call to an undefined method CodeIgniter\Database\BaseBuilder::findAll().
```

**CodeIgniter 4 version**
develop

**Expected behavior, and steps to reproduce if appropriate**
no error during phpstan checking

**Context**
 - Win 10 Pro
 - Apache 2.4.46
 - PHP version 7.4.11

**Comment by hurtsky** [comment] 2021-04-08 09:01
looks like this error appear because im using new `$userDetails = new UsersModel();`  , using `$userDetails = model('App\Models\UsersModel');` fix the error.. but im not sure if this suppose to be errors

**Comment by MGatner** [comment] 2021-04-08 12:36
This is a duplicate of #4509

**Closed** 2021-04-08 13:07 UTC
Labels: bug, duplicate
