### ISSUE TITLE
Bug: [Session] Redis - write_close_session

### ISSUE THREAD

**Issue by gabriel-joy** [codeigniter4/CodeIgniter4#7695] opened 2023-07-11 08:38 UTC
### PHP Version

8.2

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

switching session filehandler to redis handler works as exepected as long as I'm not using session_write_close.

calling session_write_close in the same script works fine but in ajax calls I get an empty session.

after session_write_close, session->destroy() generate an exception as well

### Steps to Reproduce

1. switch to redis file handler
set in 
public $sessionDriver = 'CodeIgniter\Session\Handlers\RedisHandler';
public string $sessionSavePath = 'tcp://localhost:6379?database=10'
2. 
set session variable in main script
call session_write_close()
3. make an ajax call and check session variables.

### Expected Output

to work like file handler

**Comment by kenjis** [comment] 2023-07-11 08:51
What is the exact error message?
How did you make an ajax call?

It would be helpful if you could show a minimal working sample code to reproduce the error.

**Comment by gabriel-joy** [comment] 2023-07-11 11:19
Not exactly my case but very close:

Just create 2 functions in your controller and call one after the other in browser (or uncomment the redirect line):
With redis the session simply not working.

public function debug1()
	{
		
		$session = \Config\Services::session();
		$session->start();
		
		$session->set("test","hola");
		session_write_close();
		
		$session = \Config\Services::session();
		$session->start();
		print_r($_SESSION, false);
		session_write_close();

           //return redirect()->redirect( base_url('home/debug2'));
	}

	public function debug2()
	{
		
		$session = \Config\Services::session();
		$session->start();
		
		print_r($_SESSION, false);
		session_write_close();
	}

**Comment by ping-yee** [comment] 2023-08-24 15:50
Out off the topic, how do I make sure the session store in Redis is working?

Because all operations of the session are performed normally after I set up the redisHandler setting in Config, but I find that there is no data stored in Redis.

**Comment by gabriel-joy** [comment] 2023-08-25 07:59
https://stackoverflow.com/questions/19257573/how-do-i-know-if-sessions-are-successfully-being-managed-by-redis

**Comment by ping-yee** [comment] 2023-08-27 07:12
@gabriel-joy Yah but the seesion isn't be saved into Redis even at the normal cases.
Can your session be successfully stored in Redis? 

```php
public function index()
    {
        $session = \Config\Services::session();
        $session->start();

        $session->set("test", "hola");

        session_write_close();

        // Output
        // Array ( [__ci_last_regenerate] => 1693119820 [test] => hola [_ci_previous_url] => http://localhost:8080/index.php/)
        print_r($_SESSION, false);
    }

```

But in Redis.

```log
root@8bef4d6a988e:/data# redis-cli keys "*"
(empty array)
```

**Comment by kenjis** [comment] 2023-09-08 06:27
@gabriel-joy Try #7887

**Comment by gabriel-joy** [comment] 2023-09-08 15:53
Yes, it's working as expected.  

Do you know when this fix will be published in the official release?
Thank you.

**Comment by kenjis** [comment] 2023-09-08 20:16
@gabriel-joy Thank you for testing!
The fix will be included in v4.4.2. It would be released in the next month.

**Closed by kenjis** 2023-09-08 20:16 UTC
Labels: bug

**Comment by gabriel-joy** [comment] 2023-09-11 17:35
@kenjis There is a performance issue with this fix. 
In my app I have a complex dialog with multiple ajax calls, with REDIS I have Session read length:1.0053s. With FILES I have Session read length:0.0058s. Otherwise, everything else works fine.
Therefore, the fix is partial, something is still missing. Sorry :(

**Comment by kenjis** [comment] 2023-09-11 22:00
The performance issue is really because of the fix?

**Comment by gabriel-joy** [comment] 2023-09-12 10:01
how could I know? I will open a new bug and hopefully someone will find out.

**Comment by kenjis** [comment] 2023-09-12 10:07
> how could I know?

Revert the change: https://github.com/codeigniter4/CodeIgniter4/pull/7887/files#diff-1a7b1fe40ddc58f0b240a268889a1952778b0631ce9db5f54cddaa359429dd60
and benchmark.

**Comment by gabriel-joy** [comment] 2023-09-12 10:34
I updated the script for performance tests, it seems that performance is not affected. Bot requests are executed in parallel not waiting for each other.
I assume for the moment my findings were related to network conditions (mobile connection) and not to REDIS handler. 

Here is the updated test code:

public function debug1()
	{
		$benchmark = \Config\Services::timer();
		$benchmark->start('read session1');
			
		$session = \Config\Services::session();
		$session->start();
		
		$session->set("test","hola");
		session_write_close();
		
		sleep(5);
		
		$session = \Config\Services::session();
		$session->start();
		print_r($_SESSION, false);
		session_write_close();
		
		$benchmark->stop('read session1');
		
		$timers = $benchmark->getTimers();
		echo('Session read length:'.$timers['read session1']['duration'].'s');
	}

	public function debug2()
	{
		$benchmark = \Config\Services::timer();
		$benchmark->start('read session2');
		
		$session = \Config\Services::session();
		$session->start();
		
		print_r($_SESSION, false);
		session_write_close();
		
		$benchmark->stop('read session2');
		$timers = $benchmark->getTimers();
		echo('Session read length:'.$timers['read session2']['duration'].'s');
	}
