### ISSUE TITLE
Bug: spark routes with new autoroute

### ISSUE THREAD

**Issue by skeyby** [codeigniter4/CodeIgniter4#6229] opened 2022-07-04 07:50 UTC
### PHP Version

8.1

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySQL 8

### What happened?

In my project I have the new autoroute on, but at the same time I have some explicit routes configured in the Routes.php.

Trying to run php spark routes I get an error about an attempt to initialise a class twice.

Setting $routes->setAutoRoute(false); solves the problem, but obviously stop the not-explicit routes from working.

```
PHP Fatal error:  Cannot declare class App\Controllers\DataServices\v1\Logs, because the name is already in use in /Users/abrancatelli/Git/octo-cloud-rorschach-engine/app/Controllers/DataServices/V1/Logs.php on line 9

[ErrorException]

Cannot declare class App\Controllers\DataServices\v1\Logs, because the name is already in use

at APPPATH/Controllers/DataServices/V1/Logs.php:9

Backtrace:
  1    [internal function]
       CodeIgniter\Debug\Exceptions()->shutdownHandler()

```  

This is an extract of my routes.php:

```
$routes->group('dataservices/v1', ['namespace' => 'App\Controllers\DataServices\v1'], static function ($routes) {
    $routes->get('streams/',                                    'Streams::list');
    $routes->get('stream/(:segment)',                           'Streams::get/$1');
    $routes->get('stream/(:segment)/logs/',                     'Logs::list/$1');
    $routes->get('stream/(:segment)/log/(:segment)',            'Logs::get/$1/$2');
    $routes->post('stream/(:segment)/logs/search',              'Logs::search/$1');
    $routes->get('stream/(:segment)/logs/search/(:segment)',    'Logs::search/$1/$2');
});

```

### Steps to Reproduce

Turn on the AutoRoute **AND** define a routing rule for a specific controller.

### Expected Output

The routes table

**Comment by kenjis** [comment] 2022-07-04 08:40
Can't reproduce.
Could you show us minimum sample code to reproduce the error?

And it seems you have `APPPATH/Controllers/DataServices/V1/Logs.php`,
then the classname should be `App\Controllers\DataServices\V1\Logs`, not `v1`.

**Comment by skeyby** [comment] 2022-07-04 09:07
Actually the path is lowercase, I guess it's CI that's it's converting to Upper Case V1... 

```
ls -l app/Controllers/DataServices/v1/Logs.php
-rw-r--r--  1 abrancatelli  staff  6084 Jun 30 23:58 app/Controllers/DataServices/v1/Logs.php

```
Maybe that's the cause of the missing match between the autorouted and the direct one?

**Comment by kenjis** [comment] 2022-07-04 22:38
> I guess it's CI that's it's converting to Upper Case V1...

Where did CI convert it?
Can you debug?

Anyway, I cannot reproduce the error. So I did not confirm the bug.

**Comment by kenjis** [comment] 2022-07-21 08:20
@skeyby Is your CI 4.2.1 clean install?

**Comment by kenjis** [comment] 2022-07-25 01:24
No feedback. Cannot confirm the bug.

**Comment by kenjis** [comment] 2022-08-06 00:56
Nobody cannot confirm this behavior.
Closing.

**Closed by kenjis** 2022-08-06 00:56 UTC
Labels: waiting for info
