### ISSUE TITLE
Update with join does not work properly

### ISSUE THREAD

**Issue by demirkaric** [codeigniter4/CodeIgniter4#5548] opened 2022-01-06 10:04 UTC
### PHP Version

7.4

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL 8.0.27-0ubuntu0.20.04.1

### What happened?

During joining data on update, query builder does not work properly. 

### Steps to Reproduce

In this sceanario I have model which uses mysql adapter. In the case of joining the query gets produced incorrectly and it throws fatal error of unrecognized column in example t2.col2. 

```
$model = new Model();
         $model->join("table2 as t2", "t2.id = t1.id", "inner")
             ->set("t1.col1", 1)->whereIn("t2.col2", [1,2,3])
             ->where("t1.col3", "val3")->update();
```
It produces query like this: 
```
UPDATE
    table1 AS t1
SET
    t1.`col1` = 1,
    t1.`updated_at` = :time :
WHERE
    t2.col2 IN(:col2 :) AND `t1`.`col3` = :col3 :
```

### Expected Output

This should be the output of example above,
```
UPDATE
    table1 AS t1
INNER JOIN table2 AS t2
ON
    t2.id = t1.`id`
SET
    t1.`col1` = 1,
    t1.`updated_at` = :time :
WHERE
    t2.col2 IN(:col2 : )AND `t1`.`col3` = :col3 :
```

**Comment by iRedds** [comment] 2022-01-06 11:01
This is not a bug. 
CI does not support JOIN for updating.

**Comment by kenjis** [comment] 2022-01-06 11:54
See https://forum.codeigniter.com/thread-80916.html

**Comment by paulbalandan** [comment] 2022-01-07 01:47
@demirkaric if you can make a working implementation for all available drivers, please open a PR.
Closing for now.

**Closed by paulbalandan** 2022-01-07 01:47 UTC
Labels: wontfix, database
