### ISSUE TITLE
Function lang() / Type of return value

### ISSUE THREAD

**Issue by klikklak** [codeigniter4/CodeIgniter4#2192] opened 2019-09-05 22:28 UTC
The type of the return value of the function lang() in Common.php / line 433 ff. is set to "string". The documentation (chapter Localization / Nested Arrays) shows that lang() also can return an array. But if you try this, you will get a TypeError ("Return value of lang() must be of the type string, array returned").

**Comment by jim-parry** [comment] 2019-09-08 18:39
Duplicate of #2075

**Closed by jim-parry** 2019-09-08 18:39 UTC
