### ISSUE TITLE
spark route issue

### ISSUE THREAD

**Issue by hatsat32** [codeigniter4/CodeIgniter4#2194] opened 2019-09-06 15:40 UTC
**description**

Normally if codeigniter 4 can't find a apropriate route, it shows 404 page. But when i started server with `php spark serve` command and enter a url that includes dot `.` and does not exist in routes, it show default `welcome_message` page.

For example
* `http://localhost:8080/page/doesnotexist` returns ci4's 404 page as usual
* `http://localhost:8080/page/does.notexist` returns welcome_message page
* `http://localhost:8080/notexist` return ci4's 404 page as as usual
* `http://localhost:8080/notexist.` return welcome_message page

when i use php's default server as fallow
```
cd public/
php -S localhost:8080
```
Results:
* `http://localhost:8080/page/doesnotexist` returns ci4's 404 page as usual
* `http://localhost:8080/page/does.notexist` returns php's not found page
* `http://localhost:8080/notexist` returns ci4's 404 page as usual
* `http://localhost:8080/notexist.` returns php's not found page

Probably this issue about CodeIgniter 4 CLI Tool but i I couldn't find where exactly it is :(

CodeIgniter 4 Version 4.0.0-rc.1
OS: Linux ubuntu 19.04
PHP version 7.2.19-0ubuntu0.19.04.2

**Comment by jim-parry** [comment] 2019-09-20 21:35
Cannot reproduce this.
All the examples you show, with php spark serve, return a CI 404

**Comment by hatsat32** [comment] 2019-09-22 07:35
sorry but I still get the same orror. I pulled ci4 github repo and tested it again.

* `http://localhost:8080/pagenotexist` CI4's 404 not found page
* `http://localhost:8080/pagenot.exist` default page (welcome_message.php)

I tested in different platforms again and get same error :(

* ubuntu 18.04.02. My remote server. with this command `php spark serve --host 0.0.0.0`
	* PHP 7.2.19-0ubuntu0.18.04.2
	* pulled ci4 github repo
* ubuntu 19.04. command: `php spark serve`
	* PHP 7.2.19-0ubuntu0.19.04.2
	* pulled ci4 github repo
* kali linux 2019.3 command: `php spark serve`
	* PHP 7.3.8-1
	* pulled ci4 github repo

I dont think this error about my environment or system. I tested 3 different systems. If you relly dont get this error, maybe more people should test it. Than we can learn what is going on here.

**Comment by lonnieezell** [comment] 2019-09-23 03:24
I can recreate it on Mac running php 7.2

**Comment by lonnieezell** [comment] 2019-10-09 03:54
This is a tricky one. When running with straight php server, it looks like it's getting a 404 because it's looking for a file named `pagenot.exist` and it can't find it so it returns a 404 before even getting into CI. 

The error seems to be happening in the `parseRequestURI` method of IncomingRequest. I haven't found a good solution yet, but at least we figured out where it's happening.

**Comment by lonnieezell** [comment] 2019-10-09 04:09
I take that back. It's happening much earlier, and likely by PHP itself. In rewrite.php it's recognizing `$_SERVER['SCRIPT_NAME']` as `/pagenot.exist` when a period is in it, but `/index.php` when no period in it.

**Comment by willnode** [comment] 2020-04-07 05:43
Any updates on this? I also stuck on this problem since I need to process files like `http://localhost:8080/uploads/avatar/1.jpg` but then the controller detect it as '/'. I have to comment out `$_SERVER['SCRIPT_NAME']` processing in `IncomingRequest.php` to get around this problem.

**Comment by willnode** [comment] 2020-04-07 06:05
I think I start making sense of this problem. Because if I put `index.php` to URI like `http://localhost:8080/index.php/uploads/avatar/1.jpg` it works, because $_SERVER['SCRIPT_NAME'] is `/index.php`.

I guess this line needs proper detection. 

https://github.com/codeigniter4/CodeIgniter4/blob/c3e545d9f2a25c61031a65ff6ed25466f1a6a278/system/HTTP/IncomingRequest.php#L724

**Comment by lonnieezell** [comment] 2020-04-07 18:26
@willnode Thanks for digging into this one. I've merged your PR so closing this one.

**Closed by lonnieezell** 2020-04-07 18:26 UTC
Labels: bug, external
