### ISSUE TITLE
Bug: Not able to change URL for the pagination

### ISSUE THREAD

**Issue by zeeforumcompany** [codeigniter4/CodeIgniter4#4918] opened 2021-07-07 13:37 UTC
**Direction**
I have created a model, on that model I used pagination.
Also I have set path. But It's not working.

I want to use page_url look like this:
controller/method/page/page_{page_num}

{page_num} is not replacing with pagination count.

**Describe the bug**
URL is not getting changed.

**CodeIgniter 4 version**
Codeigniter 4

**Affected module(s)**
Pager

**Expected behavior, and steps to reproduce if appropriate**
The {page_num} should replace pagination number. And first page url can also be customized.

```
$model = new NewsModel();
$paginate = $model->paginate(2, 'default', null, 3);
$model->pager->setPath('pages/news/page_{page_num}');
echo $model->pager->links();

```
**Context**
 - OS: Windows 10
 - Web server [Apache 1.2.3]
 - PHP version [8.0.1]

**Comment by paulbalandan** [comment] 2021-07-19 10:11
I cannot find this documented in the Pagination class. Are you sure we have this feature?

**Comment by zeeforumcompany** [comment] 2021-07-19 11:24
No it was in codeigniter 3 but not in 4.

**Comment by paulbalandan** [comment] 2021-07-19 12:21
This is not a bug, then. Closing.

@zeeforumcompany , if you want this feature incorporated to CI4, you can port it from v3 and open a PR. Please target `4.2` branch if you're making a PR. Thanks.

**Closed by paulbalandan** 2021-07-19 12:21 UTC
