### ISSUE TITLE
Entity returns null when used on the model

### ISSUE THREAD

**Issue by Try-Parser** [codeigniter4/CodeIgniter4#2838] opened 2020-04-17 17:23 UTC
When i extends the class with Entity it returns null when used in model query as  `returnType` also when use in insert it insert null values but when i removed the CodeIgniter\Entity class from the Entity class it will display a good object is there any reason why this is happening ? i really appreciate any kind of help thanks.

```
object(App\Entities\User)#66 (16) {
  ["id"]=>
  NULL
  ["email"]=>
  NULL
  ["username"]=>
  NULL
  ["password":protected]=>
  NULL
  ["created_by"]=>
  NULL
  ["deleted"]=>
  bool(false)
  ["disabled"]=>
  bool(false)
  ["role"]=>
  NULL
  ["created_at"]=>
  NULL
  ["updated_at"]=>
  NULL
  ["datamap":protected]=>
  array(0) {
  }
  ["dates":protected]=>
  array(3) {
    [0]=>
    string(10) "created_at"
    [1]=>
    string(10) "updated_at"
    [2]=>
    string(10) "deleted_at"
  }
  ["casts":protected]=>
  array(0) {
  }
  ["attributes":protected]=>
  array(10) {
    ["id"]=>
    string(1) "1"
    ["email"]=>
    string(14) "test@gmail.com"
    ["username"]=>
    string(4) "test"
    ["password"]=>
    string(60) "$2y$10$kDCaVVL2DpumXrRcV4pKqO2QjAqIl8g6NtVoPdRoFIKVGRFS9n3VK"
    ["created_at"]=>
    string(19) "2020-04-17 16:55:48"
    ["created_by"]=>
    string(1) "1"
    ["deleted"]=>
    string(1) "0"
    ["disabled"]=>
    string(1) "0"
    ["role"]=>
    string(10) "ADMIN,USER"
    ["updated_at"]=>
    string(19) "2020-04-17 16:55:48"
  }
  ["original":protected]=>
  array(10) {
    ["id"]=>
    string(1) "1"
    ["email"]=>
    string(14) "test@gmail.com"
    ["username"]=>
    string(4) "test"
    ["password"]=>
    string(60) "$2y$10$kDCaVVL2DpumXrRcV4pKqO2QjAqIl8g6NtVoPdRoFIKVGRFS9n3VK"
    ["created_at"]=>
    string(19) "2020-04-17 16:55:48"
    ["created_by"]=>
    string(1) "1"
    ["deleted"]=>
    string(1) "0"
    ["disabled"]=>
    string(1) "0"
    ["role"]=>
    string(10) "ADMIN,USER"
    ["updated_at"]=>
    string(19) "2020-04-17 16:55:48"
  }
  ["_cast":"CodeIgniter\Entity":private]=>
  bool(true)
}
```

**Comment by lonnieezell** [comment] 2020-04-17 20:48
Please ask on the forums where others can help out. Providing code samples is always good, too, otherwise no one really knows. I can say that I've never run into this before so pretty sure it's not a bug. Closing unless we decide otherwise.

**Closed by lonnieezell** 2020-04-17 20:48 UTC

**Comment by Try-Parser** [comment] 2020-05-22 12:42
actually when extend the model in this it will occur the error i  i removed it.
