### ISSUE TITLE
Bug: previous_url() contains current URL after reloading a page.

### ISSUE THREAD

**Issue by yyil** [codeigniter4/CodeIgniter4#4299] opened 2021-02-18 03:52 UTC
**Describe the bug**
I use previous_url() for a "Go back" button. The page sometimes needs to be reloaded. After reloading, the button's href is no longer assigned the original previous_url, but the current URL -- hence the back button does nothing.

**CodeIgniter 4 version**
4.1.1

**Expected behaviour, and steps to reproduce if appropriate**
I'd expect the previous_url() value to be retained after I reload the page. For example, clicking the "back" button on the browser doesn't care that I've reloaded the page; it takes me to the previous page.

**Context**
 - OS: MacOS 11.1
 - PHP version 7.4.9

**Comment by MGatner** [comment] 2021-02-23 21:39
I don't think this can change. Because of the backend nature of PHP each page load has to encapsulate everything it will do, and other than session data there isn't a real sense of "last" or "next". The issue is that as soon as your page has loaded, the previous URL is recorded so when you press "refresh" there is no concept of "the previous previous URL", nor do we probably want to get into that business.

There are lots of libraries around breadcrumbs that may help with this or you could create your own version using `session()`.

**Comment by yyil** [comment] 2021-02-23 22:09
Fair enough.
I opted for href="javascript:history.back();"

**Comment by MGatner** [comment] 2021-02-24 12:17
I think that is a wonderful frontend solution. Can I close this issue now?

**Comment by yyil** [comment] 2021-02-24 21:57
Yes, thank you for the explanation.

**Closed** 2021-02-25 13:16 UTC
Labels: bug
