### ISSUE TITLE
Bug: DebugBar Uncaught TypeError: btn is null

### ISSUE THREAD

**Issue by hunter-and1** [codeigniter4/CodeIgniter4#5683] opened 2022-02-12 13:10 UTC
### PHP Version

7.4

### CodeIgniter4 Version

4.1.8

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

give me error in console
DebugBar Uncaught TypeError: btn is null
![image](https://user-images.githubusercontent.com/15271465/153712748-bb5756e8-0c2c-4554-b624-b08cda907bf7.png)
![image](https://user-images.githubusercontent.com/15271465/153712770-5e45dd9d-b163-4f34-8f13-ed7bf05c9d06.png)

### Steps to Reproduce

i dont know but i using iframe in my project maybe he open twise or sameting like that i dont ik 

### Expected Output

noting

**Comment by kenjis** [comment] 2022-02-18 03:44
I can't reproduce it, so I can't confirm the bug.

**Comment by kenjis** [comment] 2022-03-26 04:28
No feedback, closing.

@hunter-and1 Sorry, we can't fix if there is no code to reproduce the bug.

**Closed by kenjis** 2022-03-26 04:28 UTC
Labels: waiting for info
