### ISSUE TITLE
Bug: session file is not found when refresh button of browser is clicked after sessionTimeToUpdate timer is up

### ISSUE THREAD

**Issue by freeaircn** [codeigniter4/CodeIgniter4#5511] opened 2021-12-28 11:40 UTC
### PHP Version

7.3

### CodeIgniter4 Version

4.1.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.3

### What happened?

1. session config: 
- sessionDriver - FileHandler
- sessionExpiration - 0
- sessionSavePath - WRITEPATH . 'session'
- sessionTimeToUpdate - 300
- sessionRegenerateDestroy - true

2. User login server successfully, and a session id is assigned to user. After sessionTimeToUpdate timer is up, user click the refresh button of brower. One of http requests during web page refreshing will get the response that session file not found.
![pic](https://user-images.githubusercontent.com/42954553/147561650-ef9c0f6d-4e72-4c42-a9b6-72e8c6c0b487.png)

3.  It affects user auth based on session checking.

### Steps to Reproduce

1. CI session config as above.
2. User login successfully, a session is assigned to the user,  and the session file is created under WRITEPATH . 'session'
3. There is no interactive operation between user and server after user login successfully.
4. 5 minutes later, the sessionTimeToUpdate timer is up.
5. User click refresh button of brower. Then, the issue, that session file is not found, will be happened as snap-picture as above.

### Expected Output

With sessionRegenerateDestroy enable, session auto-update process should work normally in the case that web page is refreshed after the sessionTimeToUpdate timer is up.

**Comment by kenjis** [comment] 2021-12-29 02:03
Can't reproduce on `develop`.
Can you check the latest develop?

```diff
--- a/app/Config/App.php
+++ b/app/Config/App.php
@@ -174,7 +174,7 @@ class App extends BaseConfig
      *
      * @var int
      */
-    public $sessionExpiration = 7200;
+    public $sessionExpiration = 0;
 
     /**
      * --------------------------------------------------------------------------
@@ -218,7 +218,7 @@ class App extends BaseConfig
      *
      * @var int
      */
-    public $sessionTimeToUpdate = 300;
+    public $sessionTimeToUpdate = 30;
 
     /**
      * --------------------------------------------------------------------------
@@ -231,7 +231,7 @@ class App extends BaseConfig
      *
      * @var bool
      */
-    public $sessionRegenerateDestroy = false;
+    public $sessionRegenerateDestroy = true;
 
     /**
      * --------------------------------------------------------------------------
diff --git a/app/Controllers/Home.php b/app/Controllers/Home.php
index 7f867e95f..df1701507 100644
--- a/app/Controllers/Home.php
+++ b/app/Controllers/Home.php
@@ -6,6 +6,6 @@ class Home extends BaseController
 {
     public function index()
     {
-        return view('welcome_message');
+        session();
     }
 }
```

Navigate to http://localhost:8080/ :
![Screenshot 2021-12-29 10 54 23](https://user-images.githubusercontent.com/87955/147620334-432c0af5-b2a5-4014-9599-dc3d8dc9a808.png)

Navigate to http://localhost:8080/ again:
![Screenshot 2021-12-29 10 57 37](https://user-images.githubusercontent.com/87955/147620361-18ca1a13-3d40-442b-8391-34eb582b9dfa.png)

**Comment by paulbalandan** [comment] 2022-01-18 09:02
No feedback, closing.

**Closed by paulbalandan** 2022-01-18 09:02 UTC
Labels: waiting for info
