### ISSUE TITLE
Bug: $builder->countAllResults(FALSE);

### ISSUE THREAD

**Issue by ciadavid** [codeigniter4/CodeIgniter4#3989] opened 2020-12-14 12:16 UTC
**Describe the bug**
Cuando utilizo un "select" personalizdo agregando campos del tipo "(SELECT x FROM table WHERE) AS Name" y despues utilizo un "HAVING". Si trato de consultar todos los resultados con "countAllResults()" me da un error de que el campo "Name" no esta en el "SELECT". 

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
Query Builder

**Expected behavior, and steps to reproduce if appropriate**
Creo que en el builder no está guardando correctamente el campo del select y al utilizar el Having este no lo encuentra.

**Context**
 - OS: Windows
 - Testing in Laragon (Apache 2.4.35 - win64 VC15)
 - PHP version 7.2.11
- MySQL 5.7.24

**Comment by ciadavid** [comment] 2020-12-14 12:17
When I use a custom "select" by adding fields of type "(SELECT x FROM table WHERE) AS Name" and then use a "HAVING". If I try to consult all the results I get an error that the "Name" field is not in the "SELECT". 
---------------------
I believe that in the builder is not saving correctly the field of the select and when using the Having this it does not find it.

**Comment by xbotkaj** [comment] 2021-02-03 21:13
> ### English version.
> When I use a custom "select" by adding fields of type "(SELECT x FROM table WHERE) AS Name" and then use a "HAVING". If I try to count all the results whit "countAllResults" I get an error that the "Name" field is not in the "SELECT".
> 
> I believe that in the builder is not saving correctly the field of the select and when using the Having this it does not find it.

Hi @ciadavid can you please paste PHP code here how you use it? I assume you want to use sub-query but I am not sure if there it problem in your code or in the framework. :)

THX

**Comment by najdanovicivan** [comment] 2021-02-13 09:47
I know the reason behind this one. There was completely same issue in CI3.

Try modifying the line in BaseBuilder class in countAllResults() method from

```
if ($this->QBDistinct === true || ! empty($this->QBGroupBy))
```
To
```
if ($this->QBDistinct === true || ! empty($this->QBGroupBy) || ! empty($this->QBHaving))
```

**Comment by kenjis** [comment] 2021-10-18 00:27
@ciadavid Thank you for reporting. 
Could you write test code to reproduce the bug?

**Comment by paulbalandan** [comment] 2022-01-18 09:05
No feedback, closing.

**Closed by paulbalandan** 2022-01-18 09:05 UTC
Labels: database, waiting for info

**Comment by austin92jus** [comment] 2023-08-04 17:58
> I know the reason behind this one. There was completely same issue in CI3.
> 
> Try modifying the line in BaseBuilder class in countAllResults() method from
> 
> ```
> if ($this->QBDistinct === true || ! empty($this->QBGroupBy))
> ```
> 
> To
> 
> ```
> if ($this->QBDistinct === true || ! empty($this->QBGroupBy) || ! empty($this->QBHaving))
> ```

thankyou its working 
why this issues never got fixed by the codeigniter developer team even on the latest version too

**Comment by kenjis** [comment] 2023-08-04 22:57
We welcome PRs: https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md
