### ISSUE TITLE
Undefined constant "CodeIgniter\CLI\STDOUT"

### ISSUE THREAD

**Issue by ericnagel** [codeigniter4/CodeIgniter4#4848] opened 2021-06-17 17:29 UTC
CodeIgniter Version: 4.1.3
PHP Version: 8.0.6
PHP SAPI: fpm-fcgi

Getting `Undefined constant "CodeIgniter\CLI\STDOUT"` error from vendor/codeigniter4/framework/system/CLI/CLI.php Line Number: 162

This was not an error before upgrading to 4.1.3; downgrading back to 4.1.2 removed this error from my project.

**Comment by paulbalandan** [comment] 2021-06-18 06:05
This is a duplicate of #4843 and will be fixed by #4844.

**Comment by paulbalandan** [comment] 2021-06-21 16:29
Fixed in [`8d09d10`](https://github.com/codeigniter4/CodeIgniter4/commit/8d09d10af1c7f0c643109b99901f72e0ea595e7c).

**Closed by paulbalandan** 2021-06-21 16:29 UTC
Labels: bug, duplicate
