### ISSUE TITLE
[Bug]:  HTMX with Toolbar on

### ISSUE THREAD

**Issue by ampmonteiro** [codeigniter4/CodeIgniter4#7965] opened 2023-09-23 14:09 UTC
### PHP Version

8.2

### CodeIgniter4 Version

4.4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

-

### What happened?

When trying htmx with CI4 (4.4) , on second call via HTMX a js error show on console with toolbar on.

### Steps to Reproduce

you see the project example here [CI + HTMX](https://github.com/ampmonteiro/ci4-4-htmx-tabs-counter)

tried with toolbar on and off.

Tried also with vanilla js ( in public folder a js file). the load script is commented in .

![image](https://github.com/codeigniter4/CodeIgniter4/assets/31895754/0eae0009-dcd2-4b38-b6cf-46a516d66853)

### Expected Output

Even toolbar only shows on dev mode, should not emit a js error.

**Comment by kenjis** [comment] 2023-09-23 20:34
The project is 404.

Use https://michalsn.github.io/codeigniter-htmx/

**Comment by ampmonteiro** [comment] 2023-09-24 09:37
@kenjis  the link is fixed. sorry about that.

And the exemple is a  simple project without external adapters. Just a pure CI4 with HTMX.

please try see again . thanks.

**Comment by kenjis** [comment] 2023-09-25 06:39
Duplicate of #7539

**Comment by kenjis** [comment] 2023-09-25 06:44
I recommend you install CodeIgniter HTMX.

**Comment by ampmonteiro** [comment] 2023-09-25 20:01
@kenjis  
Hi,
 why i have to install a extra package just to avoid this problem ?
 i read the issue #7539 and  dont agree with argue that the fault is not on CI.

As i said., in prod mode or when the filter of toolbar is off there is not problem or any error. 

Here the problem is not on HTMX and not on CI framework Core Itself  but on a tool provide by CI framework to be  used only in Dev mode.

As such, the problem in on Toolbar.  Now saying   "The issue has nothing to do with CodeIgniter since HTMX is a third-party library" make no sense. 

Another thing is you saying that the problem on toolbar when using HTMX will not be fix, fine by me.  

So  if  for you this  is not a bug, you are free to close this issue. Thanks. ;)

**Comment by kenjis** [comment] 2023-09-25 20:16
Thank you for your opinion.

If you want to solve the issue now, I recommend you install the package.
But you don't seem to want to install it.

Why don't you fix it and send a PR?
https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md

Frankly, I think it is an exaggeration to say that "the issue has nothing to do with CodeIgniter". 
But it is also true that we can't expect CodeIgniter to be fully compatible out of the box with every library out there.

If it is really a bug in CodeIgniter, or it can be fixed, it would be better to fix it.

**Comment by ampmonteiro** [comment] 2023-09-25 20:31
@kenjis 

the fix is simple, just turn off  toolbar / deactivate toolbar filter, as i already mention on issue itself. 

This issue does not affect in prod.  This not a PHP problem is more js problem on Toolbar.  
 
you have two options:
-  fix the toolbar 
- or mention problem on the docs with this problem how you can simple avoid when using HTMX with toolbar, just disable it or using / install, unnecessary package in my opinion, package that you mention and close the issue.

Nothing more to say because already repeat myself 3+ times. ;)

**Comment by kenjis** [comment] 2023-09-25 20:36
> the fix is simple, just turn off toolbar / deactivate toolbar filter, as i already mention on issue itself.

It is not a fix, but a workaround, if it is a bug.

Why don't you fix the toolbar and send a PR if you think it is a bug in CodeIgniter?

**Closed** 2024-01-20 08:56 UTC
Labels: duplicate

**Comment by kenjis** [comment] 2024-01-20 09:04
Please don't expect CodeIgniter to be fully compatible out of the box with every library out there.
