### ISSUE TITLE
Bug: [Postgres] `QueryBuilder::updateBatch()` pg_affected_rows(): Argument #1 ($result) must be of type PgSql\Result, bool given

### ISSUE THREAD

**Issue by Onerosolutions** [codeigniter4/CodeIgniter4#7387] opened 2023-03-27 05:13 UTC
### PHP Version

8.1

### CodeIgniter4 Version

4.3.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

PostgeSQL 15

### What happened?

Error after run $this->modelName->updateBatch($updatedData, 'id');

```json
{
    "title": "TypeError",
    "type": "TypeError",
    "code": 500,
    "message": "pg_affected_rows(): Argument #1 ($result) must be of type PgSql\\Result, bool given",
    "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php",
    "line": 172,
    "trace": [
        {
            "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php",
            "line": 172,
            "function": "pg_affected_rows",
            "args": [
                false
            ]
        },
        {
            "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Database\\BaseBuilder.php",
            "line": 1802,
            "function": "affectedRows",
            "class": "CodeIgniter\\Database\\Postgre\\Connection",
            "type": "->",
            "args": []
        },
        {
            "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Database\\BaseBuilder.php",
            "line": 2562,
            "function": "batchExecute",
            "class": "CodeIgniter\\Database\\BaseBuilder",
            "type": "->",
            "args": [
                "_updateBatch",
                100
            ]
        },
        {
            "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Model.php",
            "line": 414,
            "function": "updateBatch",
            "class": "CodeIgniter\\Database\\BaseBuilder",
            "type": "->",
            "args": [
                [
                    {
                        "package_plan_id": "PP63aa9a4a1f221",
                        "package_plan_name": "Basic",
                        "package_plan_description": "The ideal solution for small businesses with an affordable price, easy to use, even for beginners.",
                        "updated_at": "2023-03-27 05:08:21"
                    },
                    {
                        "package_plan_id": "PP63aa9a4a1f252",
                        "package_plan_name": "Business",
                        "package_plan_description": "The perfect package for mid-size companies, various additional features to market, sell & support your business.",
                        "updated_at": "2023-03-27 05:08:21"
                    },
                    {
                        "package_plan_id": "PP63aa9a4a1f26d",
                        "package_plan_name": "Professional",
                        "package_plan_description": "Complete features for complex needs, bring value to customers and create the best user experience.",
                        "updated_at": "2023-03-27 05:08:21"
                    }
                ],
                "package_plan_id",
                100
            ]
        },
```

### Steps to Reproduce

Run updateBatch method
$this->modelName->updateBatch($updatedData, 'id');

### Expected Output

No error.

**Comment by kenjis** [comment] 2023-03-27 08:18
It seems there is no `id` in `$updatedData`.

**Comment by kenjis** [comment] 2023-03-27 08:30
This test passes: https://github.com/codeigniter4/CodeIgniter4/blob/10e3300cce54ea8be06d560c1105dffa0a7c677a/tests/system/Models/EventsModelTest.php#L198
Can you show the failed test case?

**Comment by Onerosolutions** [comment] 2023-03-28 03:29
> ```json
> package_plan_id
> ```

i mean $this->packagePlanModel->updateBatch($updatedData, 'package_plan_id');

id is using package_plan_id

**Comment by Onerosolutions** [comment] 2023-03-28 03:59
Same issue when im run insertBatch:

```
// module_ms
            $modules = [
                [
                    'module_uuid' => $uuidGenerator::uuid4()->toString(),
                    'module_name' => 'Contact',
                    'module_description' => 'Module for contact',
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'module_uuid' => $uuidGenerator::uuid4()->toString(),
                    'module_name' => 'Deal',
                    'module_description' => 'Module for Sales Funnel',
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'module_uuid' => $uuidGenerator::uuid4()->toString(),
                    'module_name' => 'Product',
                    'module_description' => 'Module for Product',
                    'created_at' => date('Y-m-d H:i:s'),
                ]
            ];

            $moduleModel->insertBatch($modules);
```

**Comment by kenjis** [comment] 2023-03-28 09:13
We cannot reproduce.
Please show us minimum working code that reproduces the error.

**Comment by iRedds** [comment] 2023-03-28 21:13
As I can see from the code, such an error can be caused by a broken SQL query.
Therefore, as @kenjis wrote, we need more information.

I'm not sure, but try wrapping your code in a try...catch
```php
try {
    $moduleModel->insertBatch($modules);
} catch (Exception $e) {
    dd($moduleModel->error());
}
```

**Comment by kenjis** [comment] 2023-04-09 00:26
@Onerosolutions Can you provide minimum code that reproduces the error? 
Or we will close this because we cannot reproduce it.

**Comment by Onerosolutions** [comment] 2023-06-13 04:18
Hello, sorry for the late reply.

The possible cause of the error may be that I added updated_at to the $allowedFields attribute as shown below:
```
class PackagePlanModel extends BaseModel
{
  protected $table = 'package_plan_ms';
  protected $primaryKey = 'package_plan_id';
  protected $returnType = 'App\Entities\PackageBuilder\PackagePlan';
  protected $useSoftDeletes = true;

  protected $allowedFields = [
    'package_plan_id',
    'package_id',
    'package_plan_name',
    'package_plan_description',
    'created_at',
    'updated_at',
  ];

....
```

Then, I tried to run updateBatch with the returnSQL parameter set to true to get the raw SQL, and the result is as follows. I tried running it manually in PostgreSQL using DBbeaver:

```
 $packagePlanModel = new PackagePlanModel();
    try {
      $sql = $packagePlanModel->updateBatch($packagePlanUpdateBatchData, 'package_plan_id', 100, true);
      print_r($sql); die;

....
```

Array
(
[0] => UPDATE "package_plan_ms"
SET
"package_plan_description" = _u."package_plan_description",
"package_plan_name" = _u."package_plan_name",
"updated_at" = _u."updated_at"
FROM (
SELECT 'The ideal solution for small businesses with an affordable price, easy to use, even for beginners.' "package_plan_description", 'PP63aa9a4a1f221' "package_plan_id", 'Basic' "package_plan_name", '2023-06-13 04:11:37' "updated_at" UNION ALL
SELECT 'The perfect package for mid-size companies, various additional features to market, sell & support your business.' "package_plan_description", 'PP63aa9a4a1f252' "package_plan_id", 'Business' "package_plan_name", '2023-06-13 04:11:37' "updated_at" UNION ALL
SELECT 'Complete features for complex needs, bring value to customers and create the best user experience.' "package_plan_description", 'PP63aa9a4a1f26d' "package_plan_id", 'Professional' "package_plan_name", '2023-06-13 04:11:37' "updated_at"
) _u
WHERE "package_plan_ms"."package_plan_id" = _u."package_plan_id"
)

but it resulted in an error like this:
```
"SQL Error [42804]: ERROR: column "updated_at" is of type timestamp without time zone but expression is of type text
Hint: You will need to rewrite or cast the expression.
Position: 155"
```
My question is, how can I cast the updated_at column when running updateBatch to become:

```UPDATE "package_plan_ms"
SET
"package_plan_description" = _u."package_plan_description",
"package_plan_name" = _u."package_plan_name",
"updated_at" = CAST(_u."updated_at" AS timestamp without time zone)
FROM (
SELECT 'The ideal solution for small businesses with an affordable price, easy to use, even for beginners.' "package_plan_description", 'PP63aa9a4a1f221' "package_plan_id", 'Basic' "package_plan_name", '2023-06-13 04:00:57'::timestamp without time zone "updated_at" UNION ALL
SELECT 'The perfect package for mid-size companies, various additional features to market, sell & support your business.' "package_plan_description", 'PP63aa9a4a1f252' "package_plan_id", 'Business' "package_plan_name", '2023-06-13 04:00:57'::timestamp without time zone "updated_at" UNION ALL
SELECT 'Complete features for complex needs, bring value to customers and create the best user experience.' "package_plan_description", 'PP63aa9a4a1f26d' "package_plan_id", 'Professional' "package_plan_name", '2023-06-13 04:00:57'::timestamp without time zone "updated_at"
) _u
WHERE "package_plan_ms"."package_plan_id" = _u."package_plan_id";```

**Comment by rdconsolo** [comment] 2023-12-02 22:00
PHP Version
8.1

CodeIgniter4 Version
4.4.3

CodeIgniter4 Installation Method
Composer (using codeigniter4/appstarter)

Which operating systems have you tested for this bug?
Windows

Which server did you use?
php spark

Database
PostgeSQL 13

What happened?
Error after $db->table('pr_ordens')->updateBatch($op_ins, 'id_pr_ordens');

Data
```
op_ins =
	Array
	(
		[0] => Array
			(
				[id_pr_ordens] => 1
				[id_pr_programas] => 11
				[posicao] => 1
				[updated_at] => 2023-12-02 18:47:52
			)

		[1] => Array
			(
				[id_pr_ordens] => 2
				[id_pr_programas] => 11
				[posicao] => 1
				[updated_at] => 2023-12-02 18:47:52
			)

)
```
Code
```
$db = \Config\Database::connect();
$db->table('pr_ordens')->updateBatch($op_ins, 'id_pr_ordens');
```

Error message when in database trasaction:

> pg_affected_rows(): Argument #1 ($result) must be of type PgSql\Result, bool given

Error message when not in trasaction:

> pg_query(): Query failed: ERROR: operator does not exist: integer = text
> LINE 10: WHERE &quot;pr_ordens&quot;.&quot;id_pr_ordens&quot; = _u.&quot;id_pr_ordens&quot;
> ^
> HINT: No operator matches the given name and argument types. You might need to add explicit type casts.

**Comment by kenjis** [comment] 2023-12-02 22:08
The same issue as this?
https://forum.codeigniter.com/showthread.php?tid=88871

**Comment by kenjis** [comment] 2023-12-02 22:12
> My question is, how can I cast the updated_at column when running updateBatch to become:

There is no way to do that now.
So we need to add a way to specify column types.

**Comment by kenjis** [comment] 2024-01-17 04:26
I sent a PR: #8426

**Comment by kenjis** [comment] 2024-01-24 09:04
Please try #8439

**Closed** 2024-01-24 23:45 UTC
Labels: bug, database
